/**
 * prisma/seed.ts
 * Prisma database seeder — creates deterministic fixture data.
 *
 * Full seed:   npx prisma db seed   (or: npm run db:seed)
 * Base seed:   npm run db:seed:base
 *   → seeds only org groups, campuses, the superadmin system user
 *     (required as a FK owner for the report template), and the
 *     default report template.  No demo users, reports, goals, or
 *     notifications are created.
 *
 * Password for all seed users: "Nlp2026!"
 */

import "dotenv/config";
import { PrismaClient } from "./generated";
import bcryptjs from "bcryptjs";
import { UserRole } from "../types/global";
import { DEFAULT_REPORT_TEMPLATE, WEEKLY_REPORT_TEMPLATE, MONTHLY_ONLY_REPORT_TEMPLATE } from "../config/reports";

// Prisma 7 "client" engine requires accelerateUrl (prisma:// URL).
// Seeds run via the Accelerate connection; DIRECT_URL is only needed for
// raw migration operations handled by prisma.config.ts / the CLI.
const prisma = new PrismaClient({
    accelerateUrl: process.env.DATABASE_URL,
} as ConstructorParameters<typeof PrismaClient>[0]);

const ORG_ID = process.env.NEXT_PUBLIC_ORG_ID ?? "harvesters-org-dev";

// --base flag: seed only org structure + template (no demo users / reports)
const BASE_ONLY = process.argv.includes("--base");
// --reset flag: delete existing seed records before re-seeding
const RESET = process.argv.includes("--reset");

// All IDs are now auto-generated by Prisma. We'll store created records in memory for reference.
const SEED_REF = {
    users: {} as Record<string, any>,
    groups: {} as Record<string, any>,
    campuses: {} as Record<string, any>,
    templates: {} as Record<string, any>,
    templateVersions: {} as Record<string, any>,
};

// Backwards-compatibility alias: some older code references `SEED_IDS`.
const SEED_IDS = SEED_REF;

// ---------------------------------------------------------------------------
// Purge helper — removes all deterministic seed records in FK-safe order
// ---------------------------------------------------------------------------

async function purgeSeedData() {
    console.log("[seed] Purging existing seed data...");

    // 1. Notifications referencing seeded users
    await prisma.notification.deleteMany({
        where: { userId: { in: Object.values(SEED_REF.users) } },
    });

    // Purge all data (order: notifications, goals, reports, templates, users, campuses, org groups)
    await prisma.notification.deleteMany({});
    await prisma.goal.deleteMany({});
    await prisma.reportEvent.deleteMany({});
    await prisma.reportMetric.deleteMany({});
    await prisma.reportSection.deleteMany({});
    await prisma.report.deleteMany({});
    await prisma.reportTemplateVersion.deleteMany({});
    await prisma.reportTemplate.deleteMany({});
    // Invite links reference users via `createdById` FK — remove them first.
    await prisma.inviteLink.deleteMany({});
    await prisma.user.deleteMany({});
    await prisma.campus.deleteMany({});
    await prisma.orgGroup.deleteMany({});
    await prisma.orgGroup.deleteMany({ where: { id: { in: Object.values(SEED_REF.groups) } } });

    console.log("[seed] ✓ Purge complete.");
}

// ---------------------------------------------------------------------------
// Modular seed functions
// ---------------------------------------------------------------------------

async function seedOrgStructure() {
    console.log("[seed] Creating org groups...");
    const nigeriaGroup = await prisma.orgGroup.create({
        data: { name: "Nigeria Group", description: "All Nigerian campuses", country: "Nigeria", isActive: true },
    });
    const ukGroup = await prisma.orgGroup.create({
        data: { name: "UK Group", description: "All UK campuses", country: "United Kingdom", isActive: true },
    });
    SEED_REF.groups.nigeria = nigeriaGroup;
    SEED_REF.groups.uk = ukGroup;

    console.log("[seed] Creating campuses...");
    const lekki = await prisma.campus.create({ data: { name: "Lekki Campus", parentId: nigeriaGroup.id, country: "Nigeria", location: "Lekki, Lagos", isActive: true } });
    const ikeja = await prisma.campus.create({ data: { name: "Ikeja Campus", parentId: nigeriaGroup.id, country: "Nigeria", location: "Ikeja, Lagos", isActive: true } });
    const abuja = await prisma.campus.create({ data: { name: "Abuja Campus", parentId: nigeriaGroup.id, country: "Nigeria", location: "Abuja FCT", isActive: true } });
    const london = await prisma.campus.create({ data: { name: "London Campus", parentId: ukGroup.id, country: "United Kingdom", location: "London", isActive: true } });
    SEED_REF.campuses.lekki = lekki;
    SEED_REF.campuses.ikeja = ikeja;
    SEED_REF.campuses.abuja = abuja;
    SEED_REF.campuses.london = london;
}

async function seedSystemUser(hashedPassword: string) {
    // The superadmin is required as the FK owner (createdById) on the report
    // template and template version records.  Even in a base-only seed we
    // need this single user record.
    console.log("[seed] Creating system superadmin user...");
    const superadmin = await prisma.user.create({
        data: {
            email: "superadmin@harvesters.org",
            firstName: "Super",
            lastName: "Admin",
            role: UserRole.SUPERADMIN,
            passwordHash: hashedPassword,
            organisationId: ORG_ID,
            isActive: true,
        },
    });
    SEED_REF.users.superadmin = superadmin;
}

async function seedDemoUsers(hashedPassword: string) {
    console.log("[seed] Creating demo users...");
    const demoDefs = [
        { email: "spo@harvesters.org", firstName: "Senior", lastName: "Pastor", role: UserRole.SPO },
        { email: "ceo@harvesters.org", firstName: "Chief", lastName: "Executive", role: UserRole.CEO },
        { email: "churchministry@harvesters.org", firstName: "Church", lastName: "Ministry", role: UserRole.CHURCH_MINISTRY },
        { email: "grouppastor@harvesters.org", firstName: "Group", lastName: "Pastor", role: UserRole.GROUP_PASTOR, orgGroupId: SEED_REF.groups.nigeria.id },
        { email: "groupadmin@harvesters.org", firstName: "Group", lastName: "Administrator", role: UserRole.GROUP_ADMIN, orgGroupId: SEED_REF.groups.nigeria.id },
        { email: "campuspastor@harvesters.org", firstName: "Campus", lastName: "Pastor", role: UserRole.CAMPUS_PASTOR, campusId: SEED_REF.campuses.lekki.id, orgGroupId: SEED_REF.groups.nigeria.id },
        { email: "campusadmin@harvesters.org", firstName: "Campus", lastName: "Administrator", role: UserRole.CAMPUS_ADMIN, campusId: SEED_REF.campuses.lekki.id, orgGroupId: SEED_REF.groups.nigeria.id },
        { email: "dataentry@harvesters.org", firstName: "Data", lastName: "Entry", role: UserRole.DATA_ENTRY, campusId: SEED_REF.campuses.ikeja.id, orgGroupId: SEED_REF.groups.nigeria.id },
    ];
    for (const def of demoDefs) {
        const user = await prisma.user.create({
            data: {
                ...def,
                passwordHash: hashedPassword,
                organisationId: ORG_ID,
                isActive: true,
            },
        });
        SEED_REF.users[user.email] = user;
    }
    // Update org group leaders and campus admins
    await prisma.orgGroup.update({ where: { id: SEED_REF.groups.nigeria.id }, data: { leaderId: SEED_REF.users["grouppastor@harvesters.org"].id } });
    await prisma.orgGroup.update({ where: { id: SEED_REF.groups.uk.id }, data: { leaderId: SEED_REF.users["spo@harvesters.org"].id } });
    await prisma.campus.update({ where: { id: SEED_REF.campuses.lekki.id }, data: { adminId: SEED_REF.users["campusadmin@harvesters.org"].id } });
    await prisma.campus.update({ where: { id: SEED_REF.campuses.ikeja.id }, data: { adminId: SEED_REF.users["dataentry@harvesters.org"].id } });
}

async function seedTemplate() {
    console.log("[seed] Creating report templates from config/reports.ts...");

    const templateConfigs = [DEFAULT_REPORT_TEMPLATE, WEEKLY_REPORT_TEMPLATE, MONTHLY_ONLY_REPORT_TEMPLATE];
    for (const config of templateConfigs) {
        console.log(`[seed]   → ${config.name}`);
        const template = await prisma.reportTemplate.create({
            data: {
                organisationId: ORG_ID,
                name: config.name,
                description: config.description,
                version: config.version,
                isActive: config.isActive,
                isDefault: config.isDefault,
                createdById: SEED_REF.users.superadmin.id,
            },
        });
        SEED_REF.templates[config.name] = template;
        for (const sec of config.sections) {
            const section = await prisma.reportTemplateSection.create({
                data: {
                    templateId: template.id,
                    name: sec.name,
                    description: sec.description,
                    order: sec.order,
                    isRequired: sec.isRequired,
                },
            });
            for (const met of sec.metrics) {
                await prisma.reportTemplateMetric.create({
                    data: {
                        sectionId: section.id,
                        name: met.name,
                        fieldType: met.fieldType,
                        calculationType: met.calculationType,
                        isRequired: met.isRequired,
                        order: met.order,
                        capturesGoal: met.capturesGoal,
                        capturesAchieved: met.capturesAchieved,
                        capturesYoY: met.capturesYoY,
                        description: met.description,
                    },
                });
            }
        }
        // Template version snapshot
        const fullTemplate = await prisma.reportTemplate.findUnique({
            where: { id: template.id },
            include: { sections: { include: { metrics: true }, orderBy: { order: "asc" } } },
        });
        const tplVersion = await prisma.reportTemplateVersion.create({
            data: {
                templateId: template.id,
                versionNumber: 1,
                snapshot: JSON.parse(JSON.stringify(fullTemplate)),
                createdById: SEED_REF.users.superadmin.id,
            },
        });
        SEED_REF.templateVersions[config.name] = tplVersion;
    }
}

// ---------------------------------------------------------------------------
// Seed all 12 DEFAULT template sections + metrics for a single report.
// `scale` is a campus-size multiplier (e.g. 1.0 = Lekki, 0.35 = London).
// Percentage-type metrics (return rates, engagement rates) are NOT scaled
// because they represent ratios, not absolute counts.
// ---------------------------------------------------------------------------
async function seedReportSections(reportId: string, scale: number) {
    const n = (base: number) => Math.max(1, Math.round(base * scale));
    const pct = (achieved: number, goal: number) =>
        goal > 0 ? parseFloat(((achieved / goal) * 100).toFixed(1)) : null;

    // ── Church Planting ──────────────────────────────────────────────────────
    const secCp = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-cp", sectionName: "Church Planting" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secCp.id, templateMetricId: "std-cp-churches", metricName: "No. of Churches to be Planted", calculationType: "SUM", monthlyGoal: n(5), monthlyAchieved: n(4), yoyGoal: n(4), computedPercentage: pct(n(4), n(5)) },
            { reportSectionId: secCp.id, templateMetricId: "std-cp-plant-cells", metricName: "No. of Plant Cells and Small Groups", calculationType: "SUM", monthlyGoal: n(10), monthlyAchieved: n(8), yoyGoal: n(7), computedPercentage: pct(n(8), n(10)) },
            { reportSectionId: secCp.id, templateMetricId: "std-cp-cell-plants", metricName: "No. of Church Plant Cells", calculationType: "SUM", monthlyGoal: n(3), monthlyAchieved: n(3), yoyGoal: n(2), computedPercentage: pct(n(3), n(3)) },
        ],
    });

    // ── Attendance ───────────────────────────────────────────────────────────
    const secAtt = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-att", sectionName: "Attendance" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secAtt.id, templateMetricId: "std-att-sun-male", metricName: "Sunday Attendance — Male", calculationType: "AVERAGE", monthlyGoal: n(1200), monthlyAchieved: n(1150), yoyGoal: n(1000), computedPercentage: pct(n(1150), n(1200)) },
            { reportSectionId: secAtt.id, templateMetricId: "std-att-sun-female", metricName: "Sunday Attendance — Female", calculationType: "AVERAGE", monthlyGoal: n(1300), monthlyAchieved: n(1190), yoyGoal: n(1100), computedPercentage: pct(n(1190), n(1300)) },
            { reportSectionId: secAtt.id, templateMetricId: "std-att-sun-children", metricName: "Sunday Attendance — Children", calculationType: "AVERAGE", monthlyGoal: n(400), monthlyAchieved: n(382), yoyGoal: n(350), computedPercentage: pct(n(382), n(400)) },
            { reportSectionId: secAtt.id, templateMetricId: "std-att-first-timers", metricName: "First Timers", calculationType: "SUM", monthlyGoal: n(150), monthlyAchieved: n(163), yoyGoal: n(130), computedPercentage: pct(n(163), n(150)) },
            { reportSectionId: secAtt.id, templateMetricId: "std-att-worker", metricName: "Worker Attendance", calculationType: "AVERAGE", monthlyGoal: n(200), monthlyAchieved: n(188), yoyGoal: n(172), computedPercentage: pct(n(188), n(200)) },
            { reportSectionId: secAtt.id, templateMetricId: "std-att-growth-track", metricName: "Growth Track Attendance", calculationType: "AVERAGE", monthlyGoal: n(120), monthlyAchieved: n(111), yoyGoal: n(98), computedPercentage: pct(n(111), n(120)) },
            { reportSectionId: secAtt.id, templateMetricId: "std-att-growth-track-uniq", metricName: "Growth Track Unique Attendance", calculationType: "SNAPSHOT", monthlyGoal: n(500), monthlyAchieved: n(462), yoyGoal: n(415), computedPercentage: pct(n(462), n(500)) },
            { reportSectionId: secAtt.id, templateMetricId: "std-att-midweek", metricName: "Midweek Attendance", calculationType: "AVERAGE", monthlyGoal: n(600), monthlyAchieved: n(574), yoyGoal: n(528), computedPercentage: pct(n(574), n(600)) },
            { reportSectionId: secAtt.id, templateMetricId: "std-att-worker-midweek", metricName: "Workers Attendance: Midweek", calculationType: "AVERAGE", monthlyGoal: n(180), monthlyAchieved: n(168), yoyGoal: n(155), computedPercentage: pct(n(168), n(180)) },
            { reportSectionId: secAtt.id, templateMetricId: "std-att-sg", metricName: "Small Group Attendance", calculationType: "AVERAGE", monthlyGoal: n(350), monthlyAchieved: n(334), yoyGoal: n(308), computedPercentage: pct(n(334), n(350)) },
            { reportSectionId: secAtt.id, templateMetricId: "std-att-cell-leaders", metricName: "Monthly Cell Leaders Attendance (Meeting)", calculationType: "SNAPSHOT", monthlyGoal: n(50), monthlyAchieved: n(47), yoyGoal: n(43), computedPercentage: pct(n(47), n(50)) },
        ],
    });

    // ── NLP ──────────────────────────────────────────────────────────────────
    const secNlp = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-nlp", sectionName: "NLP" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secNlp.id, templateMetricId: "std-nlp-cells", metricName: "No. of NLP Cells", calculationType: "SNAPSHOT", monthlyGoal: n(25), monthlyAchieved: n(23), yoyGoal: n(20), computedPercentage: pct(n(23), n(25)) },
            { reportSectionId: secNlp.id, templateMetricId: "std-nlp-leads", metricName: "NLP Leads", calculationType: "SUM", monthlyGoal: n(100), monthlyAchieved: n(94), yoyGoal: n(85), computedPercentage: pct(n(94), n(100)) },
            { reportSectionId: secNlp.id, templateMetricId: "std-nlp-mobilizers", metricName: "Mobilizers", calculationType: "SUM", monthlyGoal: n(30), monthlyAchieved: n(27), yoyGoal: n(24), computedPercentage: pct(n(27), n(30)) },
        ],
    });

    // ── Salvation ────────────────────────────────────────────────────────────
    const secSal = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-sal", sectionName: "Salvation" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secSal.id, templateMetricId: "std-sal-service", metricName: "Soul Saved in Service", calculationType: "SUM", monthlyGoal: n(200), monthlyAchieved: n(195), yoyGoal: n(180), computedPercentage: pct(n(195), n(200)), comment: "Strong altar call responses across all services." },
            { reportSectionId: secSal.id, templateMetricId: "std-sal-cell", metricName: "Soul Saved in Cell", calculationType: "SUM", monthlyGoal: n(50), monthlyAchieved: n(44), yoyGoal: n(38), computedPercentage: pct(n(44), n(50)) },
            { reportSectionId: secSal.id, templateMetricId: "std-sal-nextgen", metricName: "Soul Saved in Next Gen", calculationType: "SUM", monthlyGoal: n(30), monthlyAchieved: n(26), yoyGoal: n(22), computedPercentage: pct(n(26), n(30)) },
            { reportSectionId: secSal.id, templateMetricId: "std-sal-baptized", metricName: "No. of People Baptized", calculationType: "SUM", monthlyGoal: n(40), monthlyAchieved: n(36), yoyGoal: n(32), computedPercentage: pct(n(36), n(40)) },
        ],
    });

    // ── Small Group ──────────────────────────────────────────────────────────
    const secSg = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-sg", sectionName: "Small Group" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secSg.id, templateMetricId: "std-sg-groups", metricName: "No. of Small Groups", calculationType: "SNAPSHOT", monthlyGoal: n(80), monthlyAchieved: n(76), yoyGoal: n(70), computedPercentage: pct(n(76), n(80)) },
            { reportSectionId: secSg.id, templateMetricId: "std-sg-leaders", metricName: "No. of Small Group Leaders", calculationType: "SNAPSHOT", monthlyGoal: n(80), monthlyAchieved: n(75), yoyGoal: n(68), computedPercentage: pct(n(75), n(80)) },
            { reportSectionId: secSg.id, templateMetricId: "std-sg-asst-leaders", metricName: "No. of Assistant Cell Leaders", calculationType: "SNAPSHOT", monthlyGoal: n(40), monthlyAchieved: n(38), yoyGoal: n(34), computedPercentage: pct(n(38), n(40)) },
            { reportSectionId: secSg.id, templateMetricId: "std-sg-cells-held", metricName: "No. of Cells that Held", calculationType: "SUM", monthlyGoal: n(200), monthlyAchieved: n(187), yoyGoal: n(172), computedPercentage: pct(n(187), n(200)) },
        ],
    });

    // ── HAEF ─────────────────────────────────────────────────────────────────
    const secHaef = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-haef", sectionName: "HAEF" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secHaef.id, templateMetricId: "std-haef-reach", metricName: "Project Reach", calculationType: "SUM", monthlyGoal: n(500), monthlyAchieved: n(478), yoyGoal: n(442), computedPercentage: pct(n(478), n(500)) },
            { reportSectionId: secHaef.id, templateMetricId: "std-haef-impact", metricName: "Project Impact", calculationType: "SUM", monthlyGoal: n(200), monthlyAchieved: n(188), yoyGoal: n(170), computedPercentage: pct(n(188), n(200)) },
        ],
    });

    // ── Discipleship ─────────────────────────────────────────────────────────
    const secDisc = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-disc", sectionName: "Discipleship" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secDisc.id, templateMetricId: "std-disc-fc-att", metricName: "Foundation Course Attendance", calculationType: "SUM", monthlyGoal: n(60), monthlyAchieved: n(56), yoyGoal: n(50), computedPercentage: pct(n(56), n(60)) },
            { reportSectionId: secDisc.id, templateMetricId: "std-disc-fc-grad", metricName: "Foundation Course Graduants", calculationType: "SUM", monthlyGoal: n(30), monthlyAchieved: n(28), yoyGoal: n(25), computedPercentage: pct(n(28), n(30)) },
            { reportSectionId: secDisc.id, templateMetricId: "std-disc-alc", metricName: "ALC Attendance", calculationType: "SUM", monthlyGoal: n(40), monthlyAchieved: n(37), yoyGoal: n(33), computedPercentage: pct(n(37), n(40)) },
            { reportSectionId: secDisc.id, templateMetricId: "std-disc-blc", metricName: "BLC Attendance", calculationType: "SUM", monthlyGoal: n(25), monthlyAchieved: n(22), yoyGoal: n(20), computedPercentage: pct(n(22), n(25)) },
            { reportSectionId: secDisc.id, templateMetricId: "std-disc-plc", metricName: "PLC Attendance", calculationType: "SUM", monthlyGoal: n(15), monthlyAchieved: n(13), yoyGoal: n(11), computedPercentage: pct(n(13), n(15)) },
            { reportSectionId: secDisc.id, templateMetricId: "std-disc-cpc", metricName: "CPC Attendance", calculationType: "SUM", monthlyGoal: n(10), monthlyAchieved: n(9), yoyGoal: n(8), computedPercentage: pct(n(9), n(10)) },
        ],
    });

    // ── Partnership ──────────────────────────────────────────────────────────
    const secPart = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-part", sectionName: "Partnership" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secPart.id, templateMetricId: "std-part-partners", metricName: "No. of Partners", calculationType: "SUM", monthlyGoal: n(500), monthlyAchieved: n(482), yoyGoal: n(445), computedPercentage: pct(n(482), n(500)) },
        ],
    });

    // ── Project ──────────────────────────────────────────────────────────────
    const secProj = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-proj", sectionName: "Project" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secProj.id, templateMetricId: "std-proj-ongoing", metricName: "No. of Ongoing Projects", calculationType: "SNAPSHOT", monthlyGoal: n(5), monthlyAchieved: n(4), yoyGoal: n(4), computedPercentage: pct(n(4), n(5)) },
            { reportSectionId: secProj.id, templateMetricId: "std-proj-phase-closure", metricName: "Project Phase and Closure", calculationType: "SNAPSHOT", monthlyGoal: n(2), monthlyAchieved: n(2), yoyGoal: n(2), computedPercentage: pct(n(2), n(2)) },
        ],
    });

    // ── Transformation ───────────────────────────────────────────────────────
    const secTrans = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-trans", sectionName: "Transformation" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secTrans.id, templateMetricId: "std-trans-testimonies", metricName: "No. of Testimonies", calculationType: "SUM", monthlyGoal: n(50), monthlyAchieved: n(46), yoyGoal: n(42), computedPercentage: pct(n(46), n(50)) },
            { reportSectionId: secTrans.id, templateMetricId: "std-trans-births", metricName: "No. of Births", calculationType: "SUM", monthlyGoal: n(10), monthlyAchieved: n(8), yoyGoal: n(7), computedPercentage: pct(n(8), n(10)) },
            { reportSectionId: secTrans.id, templateMetricId: "std-trans-dedications", metricName: "No. of Babies Dedicated", calculationType: "SUM", monthlyGoal: n(8), monthlyAchieved: n(7), yoyGoal: n(6), computedPercentage: pct(n(7), n(8)) },
            { reportSectionId: secTrans.id, templateMetricId: "std-trans-weddings", metricName: "No. of Weddings", calculationType: "SUM", monthlyGoal: n(5), monthlyAchieved: n(4), yoyGoal: n(4), computedPercentage: pct(n(4), n(5)) },
        ],
    });

    // ── Assimilation ─────────────────────────────────────────────────────────
    const secAssim = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-assim", sectionName: "Assimilation" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secAssim.id, templateMetricId: "std-assim-sg", metricName: "No. Assimilated into Small Groups", calculationType: "SUM", monthlyGoal: n(80), monthlyAchieved: n(74), yoyGoal: n(66), computedPercentage: pct(n(74), n(80)) },
            { reportSectionId: secAssim.id, templateMetricId: "std-assim-workforce", metricName: "No. Assimilated into Work Force", calculationType: "SUM", monthlyGoal: n(40), monthlyAchieved: n(37), yoyGoal: n(33), computedPercentage: pct(n(37), n(40)) },
            { reportSectionId: secAssim.id, templateMetricId: "std-assim-workers", metricName: "No. of Workers", calculationType: "SNAPSHOT", monthlyGoal: n(350), monthlyAchieved: n(338), yoyGoal: n(312), computedPercentage: pct(n(338), n(350)) },
            { reportSectionId: secAssim.id, templateMetricId: "std-assim-leaders", metricName: "No. of Leaders", calculationType: "SNAPSHOT", monthlyGoal: n(120), monthlyAchieved: n(114), yoyGoal: n(104), computedPercentage: pct(n(114), n(120)) },
        ],
    });

    // ── Next Gen ─────────────────────────────────────────────────────────────
    const secNg = await prisma.reportSection.create({
        data: { reportId, templateSectionId: "std-ng", sectionName: "Next Gen" },
    });
    await prisma.reportMetric.createMany({
        data: [
            { reportSectionId: secNg.id, templateMetricId: "std-ng-att-kidzone", metricName: "Next Gen Attendance — Kidzone", calculationType: "AVERAGE", monthlyGoal: n(300), monthlyAchieved: n(287), yoyGoal: n(262), computedPercentage: pct(n(287), n(300)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-att-stir", metricName: "Next Gen Attendance — Stir House", calculationType: "AVERAGE", monthlyGoal: n(250), monthlyAchieved: n(238), yoyGoal: n(218), computedPercentage: pct(n(238), n(250)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-ft-kidzone", metricName: "First Timers — Kidzone", calculationType: "SUM", monthlyGoal: n(20), monthlyAchieved: n(18), yoyGoal: n(15), computedPercentage: pct(n(18), n(20)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-ft-stir", metricName: "First Timers — Stir House", calculationType: "SUM", monthlyGoal: n(15), monthlyAchieved: n(14), yoyGoal: n(12), computedPercentage: pct(n(14), n(15)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-wrkr-kidzone", metricName: "Workers Attendance — Kidzone", calculationType: "AVERAGE", monthlyGoal: n(30), monthlyAchieved: n(28), yoyGoal: n(25), computedPercentage: pct(n(28), n(30)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-wrkr-stir", metricName: "Workers Attendance — Stir House", calculationType: "AVERAGE", monthlyGoal: n(25), monthlyAchieved: n(23), yoyGoal: n(21), computedPercentage: pct(n(23), n(25)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-bap-water-kz", metricName: "No. of Baptized (Water) — Kidzone", calculationType: "SUM", monthlyGoal: n(5), monthlyAchieved: n(4), yoyGoal: n(4), computedPercentage: pct(n(4), n(5)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-bap-water-sh", metricName: "No. of Baptized (Water) — Stir House", calculationType: "SUM", monthlyGoal: n(5), monthlyAchieved: n(4), yoyGoal: n(3), computedPercentage: pct(n(4), n(5)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-bap-hg-kz", metricName: "No. of Baptized (Holy Ghost) — Kidzone", calculationType: "SUM", monthlyGoal: n(8), monthlyAchieved: n(7), yoyGoal: n(6), computedPercentage: pct(n(7), n(8)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-bap-hg-sh", metricName: "No. of Baptized (Holy Ghost) — Stir House", calculationType: "SUM", monthlyGoal: n(8), monthlyAchieved: n(6), yoyGoal: n(5), computedPercentage: pct(n(6), n(8)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-return-kidzone", metricName: "Next Gen Return Rate — Kidzone", calculationType: "SNAPSHOT", monthlyGoal: 75, monthlyAchieved: 72, yoyGoal: 68, computedPercentage: pct(72, 75) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-return-stir", metricName: "Next Gen Return Rate — Stir House", calculationType: "SNAPSHOT", monthlyGoal: 70, monthlyAchieved: 66, yoyGoal: 62, computedPercentage: pct(66, 70) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-pdpf-kidzone", metricName: "No. of PD/PF Participants — Kidzone", calculationType: "SUM", monthlyGoal: n(40), monthlyAchieved: n(36), yoyGoal: n(32), computedPercentage: pct(n(36), n(40)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-pdpf-stir", metricName: "No. of PD/PF Participants — Stir House", calculationType: "SUM", monthlyGoal: n(35), monthlyAchieved: n(31), yoyGoal: n(28), computedPercentage: pct(n(31), n(35)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-teen-leaders", metricName: "No. of Teen Leaders — Stir House", calculationType: "SNAPSHOT", monthlyGoal: n(20), monthlyAchieved: n(18), yoyGoal: n(16), computedPercentage: pct(n(18), n(20)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-served-kidzone", metricName: "No. that Served — Kidzone", calculationType: "SNAPSHOT", monthlyGoal: n(30), monthlyAchieved: n(28), yoyGoal: n(25), computedPercentage: pct(n(28), n(30)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-served-stir", metricName: "No. that Served — Stir House", calculationType: "SNAPSHOT", monthlyGoal: n(25), monthlyAchieved: n(23), yoyGoal: n(21), computedPercentage: pct(n(23), n(25)) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-parental-kidzone", metricName: "Parental Engagement Rate — Kidzone", calculationType: "SNAPSHOT", monthlyGoal: 60, monthlyAchieved: 56, yoyGoal: 52, computedPercentage: pct(56, 60) },
            { reportSectionId: secNg.id, templateMetricId: "std-ng-parental-stir", metricName: "Parental Engagement Rate — Stir House", calculationType: "SNAPSHOT", monthlyGoal: 55, monthlyAchieved: 51, yoyGoal: 47, computedPercentage: pct(51, 55) },
        ],
    });
}

async function seedReports() {
    const now = new Date();
    console.log("[seed] Creating sample reports...");

    const reportConfigs = [
        { id: "report-lekki-draft", title: "Lekki Campus — Week 1, January 2025", campusId: SEED_REF.campuses.lekki, groupId: SEED_REF.groups.nigeria, status: "DRAFT" as const, createdById: SEED_REF.users.campusAdmin },
        { id: "report-lekki-submitted", title: "Lekki Campus — Week 2, January 2025", campusId: SEED_REF.campuses.lekki, groupId: SEED_REF.groups.nigeria, status: "SUBMITTED" as const, createdById: SEED_REF.users.campusAdmin, submittedById: SEED_REF.users.campusAdmin },
        { id: "report-ikeja-approved", title: "Ikeja Campus — Week 1, January 2025", campusId: SEED_REF.campuses.ikeja, groupId: SEED_REF.groups.nigeria, status: "APPROVED" as const, createdById: SEED_REF.users.dataEntry, submittedById: SEED_REF.users.dataEntry, approvedById: SEED_REF.users.campusPastor, isDataEntry: true, dataEntryById: SEED_REF.users.dataEntry },
        { id: "report-abuja-edits", title: "Abuja Campus — Week 1, January 2025", campusId: SEED_REF.campuses.abuja, groupId: SEED_REF.groups.nigeria, status: "REQUIRES_EDITS" as const, createdById: SEED_REF.users.campusAdmin },
        { id: "report-london-locked", title: "London Campus — Week 1, January 2025", campusId: SEED_REF.campuses.london, groupId: SEED_REF.groups.uk, status: "LOCKED" as const, createdById: SEED_REF.users.campusPastor, submittedById: SEED_REF.users.campusPastor, approvedById: SEED_REF.users.groupAdmin, reviewedById: SEED_REF.users.groupPastor, lockedAt: now },
    ];

    for (const rc of reportConfigs) {
        await prisma.report.create({
            data: {
                id: rc.id,
                title: rc.title,
                templateId: SEED_IDS.templates.default,
                templateVersionId: SEED_IDS.templateVersions.default,
                campusId: rc.campusId,
                orgGroupId: rc.groupId,
                periodType: "WEEKLY",
                periodYear: 2025,
                periodMonth: 1,
                periodWeek: 1,
                status: rc.status,
                createdById: rc.createdById,
                submittedById: rc.submittedById,
                approvedById: rc.approvedById,
                reviewedById: rc.reviewedById,
                isDataEntry: rc.isDataEntry ?? false,
                dataEntryById: rc.dataEntryById,
                deadline: new Date(2025, 0, 12),
                lockedAt: rc.lockedAt,
            },
        });
    }

    // Sections + metrics for all reports — all 12 DEFAULT template sections,
    // scaled by campus size so values are realistic for each location.
    console.log("[seed] Creating report sections and metrics...");
    await seedReportSections("report-lekki-draft", 1.00);
    await seedReportSections("report-lekki-submitted", 1.00);
    await seedReportSections("report-ikeja-approved", 0.75);
    await seedReportSections("report-abuja-edits", 0.85);
    await seedReportSections("report-london-locked", 0.35);

    console.log("[seed] Creating report events...");
    const tMinus = (minutesAgo: number) => new Date(Date.now() - minutesAgo * 60 * 1000);

    await prisma.reportEvent.createMany({
        data: [
            { reportId: "report-lekki-draft", eventType: "CREATED", actorId: SEED_IDS.users.campusAdmin, timestamp: tMinus(120), newStatus: "DRAFT" },
            { reportId: "report-lekki-submitted", eventType: "CREATED", actorId: SEED_IDS.users.campusAdmin, timestamp: tMinus(180), newStatus: "DRAFT" },
            { reportId: "report-lekki-submitted", eventType: "SUBMITTED", actorId: SEED_IDS.users.campusAdmin, timestamp: tMinus(60), previousStatus: "DRAFT", newStatus: "SUBMITTED" },
            { reportId: "report-ikeja-approved", eventType: "DATA_ENTRY_CREATED", actorId: SEED_IDS.users.dataEntry, timestamp: tMinus(300), newStatus: "DRAFT" },
            { reportId: "report-ikeja-approved", eventType: "SUBMITTED", actorId: SEED_IDS.users.dataEntry, timestamp: tMinus(240), previousStatus: "DRAFT", newStatus: "SUBMITTED" },
            { reportId: "report-ikeja-approved", eventType: "APPROVED", actorId: SEED_IDS.users.campusPastor, timestamp: tMinus(180), previousStatus: "SUBMITTED", newStatus: "APPROVED", details: "Figures look good. Approved." },
            { reportId: "report-abuja-edits", eventType: "CREATED", actorId: SEED_IDS.users.campusAdmin, timestamp: tMinus(360), newStatus: "DRAFT" },
            { reportId: "report-abuja-edits", eventType: "SUBMITTED", actorId: SEED_IDS.users.campusAdmin, timestamp: tMinus(300), previousStatus: "DRAFT", newStatus: "SUBMITTED" },
            { reportId: "report-abuja-edits", eventType: "EDIT_REQUESTED", actorId: SEED_IDS.users.campusPastor, timestamp: tMinus(120), previousStatus: "SUBMITTED", newStatus: "REQUIRES_EDITS", details: "Attendance figures seem inconsistent." },
            { reportId: "report-london-locked", eventType: "CREATED", actorId: SEED_IDS.users.campusPastor, timestamp: tMinus(600), newStatus: "DRAFT" },
            { reportId: "report-london-locked", eventType: "SUBMITTED", actorId: SEED_IDS.users.campusPastor, timestamp: tMinus(480), previousStatus: "DRAFT", newStatus: "SUBMITTED" },
            { reportId: "report-london-locked", eventType: "APPROVED", actorId: SEED_IDS.users.groupAdmin, timestamp: tMinus(360), previousStatus: "SUBMITTED", newStatus: "APPROVED" },
            { reportId: "report-london-locked", eventType: "REVIEWED", actorId: SEED_IDS.users.groupPastor, timestamp: tMinus(240), previousStatus: "APPROVED", newStatus: "REVIEWED" },
            { reportId: "report-london-locked", eventType: "LOCKED", actorId: SEED_IDS.users.superadmin, timestamp: tMinus(60), previousStatus: "REVIEWED", newStatus: "LOCKED" },
        ],
    });

    console.log("[seed] Creating goals...");
    const campusGoalDefs = [
        { campusId: SEED_IDS.campuses.lekki, metrics: { "std-att-sun-male": 1200, "std-att-first-timers": 150, "std-sal-service": 200, "std-assim-workers": 350, "std-ng-att-stir": 600 } },
        { campusId: SEED_IDS.campuses.ikeja, metrics: { "std-att-sun-male": 900, "std-att-first-timers": 100, "std-sal-service": 140, "std-assim-workers": 240 } },
        { campusId: SEED_IDS.campuses.abuja, metrics: { "std-att-sun-male": 1000, "std-att-first-timers": 120, "std-sal-service": 160, "std-assim-workers": 280 } },
        { campusId: SEED_IDS.campuses.london, metrics: { "std-att-sun-male": 450, "std-att-first-timers": 50, "std-sal-service": 70, "std-assim-workers": 130 } },
    ];

    for (const def of campusGoalDefs) {
        const groupId = def.campusId === SEED_IDS.campuses.london ? SEED_IDS.groups.uk : SEED_IDS.groups.nigeria;
        for (const [metricId, target] of Object.entries(def.metrics)) {
            await prisma.goal.create({
                data: {
                    campusId: def.campusId,
                    orgGroupId: groupId,
                    templateId: SEED_IDS.templates.default,
                    templateMetricId: metricId,
                    metricName: metricId,
                    mode: "ANNUAL",
                    year: 2026,
                    targetValue: target,
                    createdById: SEED_IDS.users.groupAdmin,
                },
            });
        }
    }

    console.log("[seed] Creating notifications...");
    await prisma.notification.createMany({
        data: [
            { userId: SEED_IDS.users.groupAdmin, type: "REPORT_SUBMITTED", title: "New Report Submitted", message: "Lekki Campus has submitted their weekly report.", relatedId: "report-lekki-submitted" },
            { userId: SEED_IDS.users.campusAdmin, type: "REPORT_EDIT_REQUESTED", title: "Edit Requested", message: "An edit has been requested on your report.", relatedId: "report-abuja-edits" },
        ],
    });
}

// ---------------------------------------------------------------------------
// Orchestrator
// ---------------------------------------------------------------------------

async function main() {
    if (RESET) {
        await purgeSeedData();
    }

    if (BASE_ONLY) {
        // Base-only seed: org structure + template (no demo users / reports)
        if (!RESET) {
            const existingGroup = await prisma.orgGroup.findFirst({ where: { name: "Nigeria Group" } });
            if (existingGroup) {
                console.log("[seed] Base data already seeded, skipping. Use --reset to overwrite.");
                return;
            }
        }

        const hashedPassword = await bcryptjs.hash("Nlp2026!", 12);
        await seedOrgStructure();
        // The superadmin user is required as the FK owner (createdById) on the
        // report template and template version — it must exist before seedTemplate().
        await seedSystemUser(hashedPassword);
        await seedTemplate();
        console.log("[seed] ✓ Base seed complete (groups, campuses, template).");
    } else {
        // Full seed: everything
        if (!RESET) {
            const existing = await prisma.user.findUnique({ where: { email: "superadmin@harvesters.org" } });
            if (existing) {
                console.log("[seed] Already seeded, skipping. Use --reset to overwrite.");
                return;
            }
        }

        const hashedPassword = await bcryptjs.hash("Nlp2026!", 12);
        await seedOrgStructure();
        await seedSystemUser(hashedPassword);
        await seedDemoUsers(hashedPassword);
        await seedTemplate();
        await seedReports();
        console.log("[seed] ✓ Seed complete");
    }
}

main()
    .catch((e) => {
        console.error("[seed] Error:", e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
