/**
 * config/content.ts
 * Every user-visible string lives here.
 * Components import CONTENT and reference by key — zero string literals in JSX.
 */

// AppContent is declared in types/global.d.ts inside `declare global` — no import needed.

export const CONTENT = {
    /* ── Navigation ──────────────────────────────────────────────────────── */
    nav: {
        dashboard: "Dashboard",
        reports: "Reports",
        aggregatedReports: "Aggregated Reports",
        templates: "Templates",
        analytics: "Analytics",
        users: "Users",
        org: "Organisation",
        inbox: "Inbox",
        invites: "Invite Links",
        settings: "Settings",
        goals: "Goals",
        bugReports: "Report a Bug",
        bugReportsManage: "Bug Reports",
        profile: "Profile",
        logout: "Logout",
        backToDashboard: "Back to Dashboard",
        quickForm: "Quick Form",
        imports: "Imports",
        bulkInvites: "Bulk Invites",
        adminConfig: "Admin Config",
    },

    /* ── Auth ─────────────────────────────────────────────────────────────── */
    auth: {
        loginTitle: "Sign In",
        loginSubtitle: "Welcome back to the Harvesters Reporting System",
        emailLabel: "Email Address",
        emailPlaceholder: "you@harvestersng.org",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter your password",
        loginButton: "Sign In",
        loggingIn: "Signing in…",
        forgotPassword: "Forgot password?",
        noAccount: "Don't have an account?",
        registerLink: "Create an account",
        registerTitle: "Create Account",
        registerSubtitle: "Set up your Harvesters Reporting System account",
        firstNameLabel: "First Name",
        lastNameLabel: "Last Name",
        firstNamePlaceholder: "Your first name",
        lastNamePlaceholder: "Your last name",
        phoneLabel: "Phone Number",
        phonePlaceholder: "+234 800 000 0000",
        registerButton: "Create Account",
        alreadyHaveAccount: "Already have an account?",
        loginLink: "Sign in",
        forgotTitle: "Reset Password",
        forgotSubtitle: "Enter your email and we'll send reset instructions",
        sendResetLink: "Send Reset Link",
        resetTitle: "Set New Password",
        resetSubtitle: "Choose a strong new password",
        newPasswordLabel: "New Password",
        confirmPasswordLabel: "Confirm Password",
        resetButton: "Reset Password",
        joinTitle: "Join via Invite",
        joinSubtitle: "Complete your registration using an invite link",
        errors: {
            invalidCredentials: "Invalid email or password.",
            serverError: "Something went wrong. Please try again.",
            emailRequired: "Email is required.",
            emailInvalid: "Please enter a valid email address.",
            passwordRequired: "Password is required.",
            passwordsDoNotMatch: "Passwords do not match.",
            passwordTooShort: "Password must be at least 8 characters.",
            invalidToken: "This invite link is invalid or has expired.",
        },
        accountInfoLabel: "Account Information",
        passwordChangedSuccess: "Password changed successfully.",
        currentPasswordLabel: "Current Password",
        changePasswordAction: "Change Password",
        profileTabLabel: "Profile",
        passwordTabLabel: "Password",
        inviteInvalidTitle: "Invalid Invite Link",
        inviteExpiredTitle: "Invite Link Expired",
        inviteUsedTitle: "Invite Already Used",
        goToLogin: "Go to Login",
        registrationSuccessTitle: "Registration Successful",
        registrationSuccessMessage: "Your account has been created. You can now sign in.",
        redirectingIn: "Redirecting to login in",
        inviteRoleLabel: "You have been invited as",
        rememberMe: "Remember me",
        haveInvite: "Have an invite link?",
        joinWithInvite: "Join with invite",
        noInvite: "No invite link?",
        registerWithoutInvite: "Create a free account",
    },

    /* ── Reports ────────────────────────────────────────────────────────── */
    reports: {
        pageTitle: "Reports",
        newReport: "New Report",
        submitReport: "Submit Report",
        saveDraft: "Save Draft",
        requestEdit: "Request Edit",
        approveReport: "Approve",
        markReviewed: "Mark Reviewed",
        lockReport: "Lock Report",
        viewReport: "View Report",
        editReport: "Edit Report",
        viewHistory: "View History",
        requestUpdate: "Request Update",
        filterByStatus: "Filter by status",
        filterByCampus: "Filter by campus",
        filterByPeriod: "Filter by period",
        filterByTemplate: "Filter by template",
        searchPlaceholder: "Search reports…",
        periodLabel: "Period",
        statusLabel: "Status",
        campusLabel: "Campus",
        groupLabel: "Group",
        deadlineLabel: "Deadline",
        submittedByLabel: "Submitted By",
        submittedAtLabel: "Submitted At",
        reviewedByLabel: "Reviewed By",
        approvedByLabel: "Approved By",
        lockedAtLabel: "Locked At",
        notesLabel: "Notes",
        notesPlaceholder: "Add any notes or context…",
        dataEntryBadge: "Data Entry",
        fieldGoal: "Goal",
        fieldAchieved: "Achieved",
        fieldYoY: "YoY Goal",
        fieldGoalComment: "Add goal comment",
        fieldAchievedComment: "Add context",
        fieldYoYComment: "Add YoY comment",
        metricComment: "Add comment",
        commentPlaceholder: "Optional context or note…",
        goalPrefilledTooltip: "Pre-filled from set goals — not editable while filling a report",
        goalFromSource: "Goal source",
        goalNotSet: "No goal set",
        goalLocked: "Goal locked",
        goalsLoading: "Loading goals…",
        goalsPrefilledBadge: "goals pre-filled",
        noGoalsSet: "No goals set for this period — enter values manually",
        statVsGoal: "vs Goal",
        statVsYoY: "vs Last Year",
        requiredFilled: "required filled",
        liveStats: "Live Statistics",
        statOverallGoal: "Overall Goal Progress",
        statYoYGrowth: "Year-on-Year Growth",
        statMetricsWithGoal: "Metrics with Goals",
        metricsFormTitle: "Report Data",
        sectionRequired: "Required",
        sectionOptional: "Optional",
        emptyState: {
            title: "No Reports Found",
            description: "No reports match your current filters.",
            newReportCta: "Submit your first report",
        },
        deleteConfirm: "Are you sure you want to delete this report?",
        submitConfirm: "Submit this report for review?",
        approveConfirm: "Approve this report?",
        lockConfirm: "Lock this report? This cannot be undone.",
        editRequestTitle: "Request Edit",
        editRequestReasonLabel: "Reason for Edit",
        editRequestReasonPlaceholder: "Describe what needs to be corrected…",
        editRequestSubmit: "Submit Edit Request",
        updateRequestTitle: "Request Update",
        updateReasonLabel: "Reason for Update",
        updateReasonPlaceholder: "Explain why this update is needed…",
        updateRequestSubmit: "Submit Update Request",
        editRequestDraftTitle: "Draft Edit",
        editRequestApprove: "Approve Edit",
        editRequestReject: "Reject Edit",
        historyTitle: "Report History",
        auditTrailTitle: "Audit Trail",
        eventLabels: {
            CREATED: "Report Created",
            SUBMITTED: "Report Submitted",
            EDIT_REQUESTED: "Edits Requested",
            EDIT_SUBMITTED: "Edit Submitted",
            EDIT_APPROVED: "Edit Approved",
            EDIT_REJECTED: "Edit Rejected",
            EDIT_APPLIED: "Edit Applied",
            TRANSLATED: "Translated",
            APPROVED: "Report Approved",
            REVIEWED: "Report Reviewed",
            LOCKED: "Report Locked",
            UNLOCKED: "Report Unlocked",
            DEADLINE_PASSED: "Deadline Passed",
            UPDATE_REQUESTED: "Update Requested",
            UPDATE_APPROVED: "Update Approved",
            UPDATE_REJECTED: "Update Rejected",
            DATA_ENTRY_CREATED: "Data Entry Submitted",
            TEMPLATE_VERSION_NOTE: "Template Version Updated",
            AUTO_APPROVED: "Auto-Approved",
        },
        sections: {
            attendanceTitle: "Weekly Attendance",
            salvationsTitle: "Salvations & First Timers",
            discipleshipTitle: "Discipleship",
            tithesTitle: "Tithes & Offerings",
            workersTitle: "Workers",
            outreachTitle: "Outreach",
            youthTitle: "Youth",
            childrenTitle: "Children",
            mediaTitle: "Media & Digital",
            prayerTitle: "Prayer",
            infrastructureTitle: "Infrastructure & Facilities",
        },
        status: {
            DRAFT: "Draft",
            SUBMITTED: "Submitted",
            REQUIRES_EDITS: "Requires Edits",
            APPROVED: "Approved",
            REVIEWED: "Reviewed",
            LOCKED: "Locked",
        },
        actions: {
            submit: "Submit",
            approve: "Approve",
            review: "Mark Reviewed",
            lock: "Lock",
            unlock: "Unlock",
            requestEdit: "Request Edit",
        },
        columnLabels: {
            report: "Report",
            title: "Title",
            campus: "Campus",
            period: "Period",
            status: "Status",
            submittedBy: "Submitted By",
            submittedAt: "Submitted At",
            deadline: "Deadline",
            createdAt: "Created",
            lockedAt: "Locked At",
            actions: "",
        },
        filterLabels: {
            status: "Status",
            campus: "Campus",
            period: "Period",
            template: "Template",
            all: "All",
        },
        metadata: {
            title: "Details",
            templateLabel: "Template",
            periodTypeLabel: "Period Type",
            yearLabel: "Year",
            weekLabel: "Week",
            monthLabel: "Month",
            createdByLabel: "Created By",
            deadlineLabel: "Deadline",
            lockedAtLabel: "Locked At",
        },
        aggregation: {
            pageTitle: "Aggregated Reports",
            pageSubtitle: "Run rollup reporting by campus/group/yearly cycles",
            back: "Back",
            selectScopeStep: "1. Select scope",
            selectPeriodStep: "2. Select period",
            selectTemplateStep: "3. Select template + metrics",
            scopeCampus: "Campus",
            scopeGroup: "Group",
            scopeAll: "All",
            selectCampus: "Select campus",
            selectGroup: "Select group",
            pickMonth: "Pick month",
            pickWeek: "Pick week",
            pickYear: "Pick year",
            allMonths: "All months",
            allWeeks: "All weeks",
            sourceReportsTag: "Source reports",
            metricsTag: "Metrics",
            templatePlaceholder: "Template",
            metricsPlaceholder: "Metrics (optional)",
            statusesPlaceholder: "Statuses",
            includeDraftsLabel: "Include draft reports",
            includeDraftsHint: "Toggle to include/exclude drafts in rollup and benchmark.",
            previewButton: "Preview Aggregation",
            generateButton: "Generate Aggregated Report",
            exportButton: "Export Aggregated Report",
            exportGroupedDetailsToggle: "Include grouped source report details sheet",
            exportGroupedDetailsHint:
                "Adds an extra export sheet grouped by org group and campus, with section and metric rows aligned for each source report.",
            ungroupedLabel: "Ungrouped",
            previewTitle: "Aggregation Preview",
            reportsIncluded: "Reports included",
            templateTag: "Template",
            sectionsTag: "Sections",
            noTemplate: "N/A",
            loadingPreviewSuccess: "Preview loaded. Verify details before generating.",
            loadingPreviewError: "Failed to preview aggregation",
            previewRequiredWarning: "Please run preview first.",
            generatedSuccess: "Aggregated report created successfully.",
            generatedError: "Failed to generate report",
            exportMissingWarning: "No aggregation preview available for export.",
            accessDeniedTitle: "Access denied",
            accessDeniedDescription: "You are not permitted to use aggregation.",
            scopeRequiredError: "Please select a scope before previewing.",
            scopeLockedHint: "Scope is fixed by your role permissions.",
        },
        export: {
            button: "Export (.xlsx)",
            dialogTitle: "Export Reports",
            scopeLabel: "Export Scope",
            scopeAll: "All filtered reports",
            scopeSelected: "Selected reports only",
            groupingLabel: "Group by",
            groupingNone: "None",
            groupingCampus: "Campus",
            groupingMonth: "Month",
            groupingQuarter: "Quarter",
            contentLabel: "Include",
            contentMetrics: "Metric values",
            contentGoals: "Goal values",
            contentComments: "Comments",
            contentStatus: "Status history",
            formatLabel: "Format",
            formatSingleSheet: "Single sheet",
            formatMultiSheet: "One sheet per campus",
            exportButtonLabel: "Export",
            cancelButtonLabel: "Cancel",
            listFilename: "harvesters-reports",
            sheetList: "Reports",
            sheetMeta: "Overview",
            sheetMetrics: "Metrics",
            colTitle: "Title",
            colCampus: "Campus",
            colPeriod: "Period",
            colStatus: "Status",
            colTemplate: "Template",
            colDeadline: "Deadline",
            colCreatedAt: "Created",
            colSubmittedBy: "Submitted By",
            colNotes: "Notes",
            colSection: "Section",
            colMetric: "Metric",
            colAchieved: "Achieved",
            colGoal: "Goal",
            colPercentage: "% of Goal",
            colComment: "Comment",
        },
    },

    /* ── Templates ────────────────────────────────────────────────────────── */
    templates: {
        pageTitle: "Report Templates",
        newTemplate: "New Template",
        editTemplate: "Edit Template",
        previewTemplate: "Preview",
        publishTemplate: "Publish",
        archiveTemplate: "Archive",
        setDefault: "Set as Default",
        versionsLabel: "Version History",
        goalPromptTitle: "Set Goals for This Template?",
        goalPromptDescription: "This template captures goals for some metrics. Setting goals now lets fillers see progress against targets in the report form.",
        goalPromptConfirm: "Set Goals Now",
        goalPromptSkip: "Set Goals Later",
        templateSaved: "Template saved.",
        templateCreated: "Template created.",
        nameLabel: "Template Name",
        namePlaceholder: "e.g. Standard Campus Weekly Report",
        descriptionLabel: "Description",
        descriptionPlaceholder: "Brief description of this template's purpose",
        addSection: "Add Section",
        addMetric: "Add Metric",
        removeSection: "Remove Section",
        sectionLabel: "Section",
        sectionsLabel: "Sections",
        sectionNameLabel: "Section Name",
        metricNameLabel: "Metric Name",
        fieldTypeLabel: "Field Type",
        calculationTypeLabel: "Calculation Method",
        isRequiredLabel: "Required",
        capturesGoalLabel: "Captures Goal",
        capturesAchievedLabel: "Captures Achieved",
        capturesYoYLabel: "Captures YoY Goal",
        defaultBadge: "Default",
        createTemplate: "Create Template",
        emptySections: "No sections yet. Click Add Section to start building this template.",
        emptyMetrics: "No metrics yet. Add a metric below.",
        emptyState: {
            title: "No Templates",
            description: "Create a report template to start collecting data.",
        },
    },

    /* ── Goals ─────────────────────────────────────────────────────────────── */
    goals: {
        pageTitle: "Goals",
        setGoal: "Set Goal",
        editGoal: "Edit Goal",
        requestUnlock: "Request Edit",
        approveUnlock: "Approve",
        rejectUnlock: "Reject",
        targetValueLabel: "Target Value",
        yearLabel: "Year",
        monthLabel: "Month",
        modeLabel: "Goal Mode",
        lockedBadge: "Locked",
        pendingUnlockBadge: "Unlock Pending",
        unlockReasonLabel: "Reason for Unlock",
        unlockReasonPlaceholder: "Explain why this goal needs to be changed\u2026",
        cancelEdit: "Cancel",
        modeAnnual: "Annual \u2014 same target each month",
        modeMonthly: "Monthly \u2014 set per month individually",
        campusLabel: "Campus",
        allCampuses: "All Campuses",
        annualTargetLabel: "Annual Target (applies to all 12 months)",
        saveGoals: "Save Goals",
        savedGoals: "Goals saved successfully.",
        templateLabel: "Template",
        months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        lockedNote: "Locked \u2014 submit an unlock request to change this goal",
        noTemplate: "No active template found. Create a template first.",
        saveAll: "Save All Goals",
        metricColumn: "Metric",
        annualTargetShort: "Target",
        bulkNote: "Set annual targets for all campuses in a single view.",
        noGoalSet: "—",
        emptyState: {
            title: "No Goals Set",
            description: "Goals help track expected performance against actuals.",
        },
    },

    /* ── Dashboard ────────────────────────────────────────────────────────── */
    dashboard: {
        pageTitle: "Dashboard",
        kpi: {
            totalReports: "Total Reports",
            pendingReview: "Pending Review",
            approvedReports: "Approved",
            complianceRate: "Compliance Rate",
            submittedOnTime: "On-Time Submissions",
            overdueReports: "Overdue",
            activeTemplates: "Active Templates",
            totalCampuses: "Total Campuses",
            totalUsers: "Total Users",
            drafts: "Drafts",
            requiresEdits: "Requires Edits",
            quarterlyCompliance: "Quarter Compliance",
        },
        welcomeBack: "Welcome back",
        recentActivity: "Recent Activity",
        noActivity: "No recent activity.",
        upcomingDeadlines: "Upcoming Deadlines",
        noDeadlines: "No upcoming deadlines.",
        cta: {
            pendingApproval: (n: number) => `There ${n === 1 ? "is" : "are"} ${n} report${n === 1 ? "" : "s"} pending approval`,
            pendingReview: (n: number) => `There ${n === 1 ? "is" : "are"} ${n} approved report${n === 1 ? "" : "s"} awaiting review sign-off`,
            draftReports: (n: number) => `You have ${n} draft report${n === 1 ? "" : "s"} in progress`,
            requiresEdits: (n: number) => `There ${n === 1 ? "is" : "are"} ${n} report${n === 1 ? "" : "s"} that require${n === 1 ? "s" : ""} edits`,
            weeklyReportDue: (period: string) => `You have a weekly report due for ${period}`,
            verifyEmail: (email: string) => `Please verify your email (${email}) to secure your account`,
            viewReports: "View Reports",
            openProfile: "Open Profile",
        },
        memberLobby: {
            title: "Welcome to Harvesters Reporting",
            subtitle: "Your account has been created successfully. An administrator will assign you a role to get started.",
            waitingLabel: "Awaiting role assignment",
            currentRole: "Current role",
            contactAdmin: "If you believe this is an error, please contact your campus administrator.",
        },
    },

    /* ── Users ───────────────────────────────────────────────────────────── */
    users: {
        pageTitle: "Users",
        inviteUser: "Invite User",
        editUser: "Edit User",
        deactivateUser: "Deactivate",
        activateUser: "Activate",
        resetPassword: "Reset Password",
        nameLabel: "Name",
        emailLabel: "Email",
        roleLabel: "Role",
        campusLabel: "Campus",
        groupLabel: "Group",
        statusLabel: "Status",
        activeStatus: "Active",
        inactiveStatus: "Inactive",
        searchPlaceholder: "Search users…",
        emptyState: {
            title: "No Users Found",
            description: "No users match your current filters.",
        },
        confirmDeactivate: "Deactivate this user? They will no longer be able to log in.",
        confirmActivate: "Reactivate this user?",
        roles: {
            SUPERADMIN: "Superadmin",
            SPO: "SPO",
            CEO: "CEO",
            OFFICE_OF_CEO: "Office of CEO",
            CHURCH_MINISTRY: "Church Ministry",
            GROUP_PASTOR: "Group Pastor",
            GROUP_ADMIN: "Group Admin",
            CAMPUS_PASTOR: "Campus Pastor",
            CAMPUS_ADMIN: "Campus Admin",
            DATA_ENTRY: "Data Entry",
            USHER: "Usher",
            MEMBER: "Member",
        },
        recentReports: "Recent Reports",
        noReports: "No reports submitted yet.",
    },

    /* ── Organisation ────────────────────────────────────────────────────── */
    org: {
        pageTitle: "Organisation",
        newGroup: "New Group",
        newCampus: "New Campus",
        editGroup: "Edit Group",
        editCampus: "Edit Campus",
        groupNameLabel: "Group Name",
        campusNameLabel: "Campus Name",
        countryLabel: "Country",
        locationLabel: "Location",
        leaderLabel: "Group Leader",
        adminLabel: "Campus Admin",
        campusesLabel: "Campuses",
        membersLabel: "Members",
        emptyStateGroups: {
            title: "No Groups",
            description: "Add an org group to begin building the hierarchy.",
        },
        emptyStateCampuses: {
            title: "No Campuses",
            description: "Add campuses to organise your reporting structure.",
        },
    },

    /* ── Analytics ────────────────────────────────────────────────────────── */
    analytics: {
        pageTitle: "Analytics",
        // Tabs
        tab: {
            overview: "Overview",
            metrics: "Metrics Analysis",
            trends: "Trends",
            compliance: "Compliance",
            quarterly: "Quarterly Summary",
        },
        // Section headings
        complianceTitle: "Report Compliance by Campus",
        trendsTitle: "Submission Trends",
        campusBreakdownTitle: "Campus Breakdown",
        statusBreakdownTitle: "Status Breakdown",
        metricTrendsTitle: "Key Metrics Over Time",
        goalVsAchievedTitle: "Goal vs. Achieved",
        yoyComparisonTitle: "Year-on-Year Comparison",
        campusMetricCompTitle: "Campus Metric Comparison",
        cumulativeTrendTitle: "Cumulative Trend",
        // Controls
        periodSelectorLabel: "Period",
        periodGranularityLabel: "Granularity",
        campusSelectorLabel: "Campus",
        groupSelectorLabel: "Group",
        metricSelectorLabel: "Metric",
        sectionSelectorLabel: "Section",
        exportButton: "Export",
        yearLabel: "Year",
        monthRangeLabel: "Month Range",
        // Granularity options
        granularity: {
            weekly: "Weekly",
            monthly: "Monthly",
            quarterly: "Quarterly",
            annual: "Annual",
        },
        // Chart labels
        chartLabels: {
            goal: "Goal",
            achieved: "Achieved",
            yoy: "Year on Year",
            submitted: "Submitted",
            approved: "Approved",
            count: "Count",
            value: "Value",
            percentage: "% Achieved",
        },
        // KPI labels
        kpi: {
            avgAchievementRate: "Avg. Achievement Rate",
            metricsTracked: "Metrics Tracked",
            campusesReporting: "Campuses Reporting",
            goalsSet: "Goals Set",
        },
        // State
        noData: "No data available for the selected period.",
        noMetricSelected: "Select a metric above to view the analysis.",
        loadingMetrics: "Loading metrics…",
        drafts: "Drafts",
        requiresEdits: "Requires Edits",
        quarterlyTitle: "Quarterly Summary",
        quarterlyComplianceLabel: "Q Compliance",
        quarterlySubmittedLabel: "Q Submitted",
        quarterlyApprovedLabel: "Q Approved",
        quarterlyQoqLabel: "vs. Previous Quarter",
        quarterlyNoData: "No data available for this quarter.",
        quarterlyTopCampuses: "Top Campuses This Quarter",
        quarterlySelector: "Quarter",
    },

    /* ── Notifications ─────────────────────────────────────────────────── */
    notifications: {
        pageTitle: "Inbox",
        markAllRead: "Mark all as read",
        emptyState: {
            title: "All Caught Up",
            description: "You have no new notifications.",
        },
        types: {
            REPORT_SUBMITTED: "Report Submitted",
            REPORT_EDIT_REQUESTED: "Edit Requested",
            REPORT_APPROVED: "Report Approved",
            REPORT_REVIEWED: "Report Reviewed",
            REPORT_LOCKED: "Report Locked",
            REPORT_UNLOCKED: "Report Unlocked",
            REPORT_EDIT_SUBMITTED: "Edit Submitted",
            REPORT_EDIT_APPROVED: "Edit Approved",
            REPORT_EDIT_REJECTED: "Edit Rejected",
            REPORT_UPDATE_REQUESTED: "Update Requested",
            REPORT_UPDATE_APPROVED: "Update Approved",
            REPORT_UPDATE_REJECTED: "Update Rejected",
            REPORT_DEADLINE_REMINDER: "Deadline Reminder",
            GOAL_UNLOCK_REQUESTED: "Goal Unlock Requested",
            GOAL_UNLOCK_APPROVED: "Goal Unlock Approved",
            GOAL_UNLOCK_REJECTED: "Goal Unlock Rejected",
            EMAIL_VERIFICATION_REQUIRED: "Email Verification",
            EMAIL_VERIFIED: "Email Verified",
            EMAIL_CHANGE_REQUESTED: "Email Change Requested",
            EMAIL_CHANGED: "Email Changed",
        },
        deadlineReminder: {
            fallbackRecipient: "there",
            fallbackReportTitle: "Report",
            title: "Deadline Reminder",
            messageTemplate: "Reminder: {reportTitle} is due on {deadline}.",
            actionLabel: "Submit Report",
        },
    },

    /* ── Common / Shared ────────────────────────────────────────────────── */
    common: {
        save: "Save",
        saving: "Saving…",
        cancel: "Cancel",
        confirm: "Confirm",
        delete: "Delete",
        edit: "Edit",
        view: "View",
        close: "Close",
        back: "Back",
        next: "Next",
        previous: "Previous",
        search: "Search",
        filter: "Filter",
        reset: "Reset",
        export: "Export",
        refresh: "Refresh",
        loading: "Loading…",
        submitting: "Submitting…",
        required: "Required",
        optional: "Optional",
        yes: "Yes",
        no: "No",
        all: "All",
        none: "None",
        unknown: "Unknown",
        activate: "Activate",
        deactivate: "Deactivate",
        noResultsTitle: "Nothing here yet",
        noResultsDescription: "Try adjusting your filters.",
        viewAll: "View all",
        successSave: "Saved successfully.",
        successDelete: "Deleted successfully.",
        errorDefault: "Something went wrong. Please try again.",
        errorNotFound: "The requested resource was not found.",
        errorUnauthorized: "You are not authorised to perform this action.",
        pagination: {
            showing: "Showing",
            to: "to",
            of: "of",
            results: "results",
        },
        darkMode: "dark mode",
        lightMode: "light mode",
        switchTo: "Switch to",
    },

    footer: {
        organization: "Harvesters International Christian Centre (HICC)",
        rights: "All rights reserved.",
        builtByLabel: "Built by",
        developerName: "S.D",
        developerUrl: "https://sotonye-dagogo.is-a.dev",
        links: [
            { label: "Home", href: "/" },
            { label: "How it works", href: "/how-it-works" },
            { label: "About", href: "/about" },
            { label: "Privacy", href: "/privacy" },
            { label: "Terms", href: "/terms" },
        ],
    },

    /* ── Profile ───────────────────────────────────────────────────────────── */
    profile: {
        pageTitle: "My Profile",
        editProfile: "Edit Profile",
        changePassword: "Change Password",
        accountInfoLabel: "Account Information",
        personalInfoLabel: "Personal Information",
        firstNameLabel: "First Name",
        lastNameLabel: "Last Name",
        emailLabel: "Email Address",
        phoneLabel: "Phone Number",
        roleLabel: "Role",
        campusLabel: "Campus",
        groupLabel: "Group",
        saveChanges: "Save Changes",
        saving: "Saving…",
        passwordSection: "Change Password",
        emailSecuritySection: "Email Verification & Change",
        emailVerificationLabel: "Email Verification",
        emailVerifiedBadge: "Verified",
        emailUnverifiedBadge: "Unverified",
        verificationStatusHint: "Verification protects your account and enables trusted email alerts.",
        verificationSentTo: "Verification email sent to",
        resendVerification: "Resend Verification Email",
        verificationEmailSent: "Verification email sent.",
        emailChangeLabel: "Change Email",
        newEmailLabel: "New Email Address",
        newEmailPlaceholder: "new-address@harvestersng.org",
        requestEmailChange: "Request Email Change",
        emailChangeRequested: "Email change confirmation sent.",
        pendingEmailLabel: "Pending Email",
        confirmViaEmailHint: "Confirm the link sent to your new email to complete this change.",
        currentPasswordLabel: "Current Password",
        newPasswordLabel: "New Password",
        confirmPasswordLabel: "Confirm New Password",
        updatePassword: "Update Password",
        passwordUpdated: "Password updated successfully.",
        profileUpdated: "Profile updated successfully.",
        memberSince: "Member Since",
        lastUpdated: "Last Updated",
        tabs: {
            profile: "Profile",
            security: "Security",
            appearance: "Appearance",
            notifications: "Notifications",
        },
    },

    /* ── Invite Links ─────────────────────────────────────────────────────── */
    invites: {
        pageTitle: "Invite Links",
        newInvite: "Generate Invite Link",
        copyLink: "Copy Link",
        copiedLink: "Copied!",
        revokeLink: "Revoke",
        targetRoleLabel: "Invite As",
        recipientEmailLabel: "Recipient Email",
        recipientEmailPlaceholder: "you@harvestersng.org",
        campusLabel: "Campus (optional)",
        groupLabel: "Group (optional)",
        expiresInLabel: "Expires In",
        noteLabel: "Internal Note",
        notePlaceholder: "e.g. For new Lagos campus admin",
        statusActive: "Active",
        statusUsed: "Used",
        statusExpired: "Expired",
        statusRevoked: "Revoked",
        expiresAtLabel: "Expires",
        usedAtLabel: "Used At",
        createdAtLabel: "Created",
        linkLabel: "Invite URL",
        generateButton: "Generate",
        emptyState: {
            title: "No Invite Links",
            description: "Generate a link to invite a new user to the system.",
        },
        expiryOptions: {
            "24": "24 hours",
            "48": "48 hours",
            "72": "72 hours (default)",
            "168": "7 days",
            "720": "30 days",
        },
        deleteConfirm: "Revoke this invite link? The URL will no longer work.",
    },
    /* ── Bug Reports ────────────────────────────────────────────────────── */
    bugReports: {
        pageTitle: "Report a Bug",
        managePageTitle: "Bug Reports",
        categoryLabel: "Issue Type",
        categoryPlaceholder: "Select an issue type",
        descriptionLabel: "Description",
        descriptionPlaceholder: "Describe the issue you encountered in detail...",
        screenshotLabel: "Screenshot (optional)",
        screenshotHint: "Upload a screenshot to help us understand the issue.",
        emailLabel: "Contact Email",
        emailPlaceholder: "you@harvestersng.org",
        submitButton: "Submit Bug Report",
        submitting: "Submitting...",
        submitSuccess: "Bug report submitted. Thank you!",
        statusLabel: "Status",
        adminNotesLabel: "Admin Notes",
        adminNotesPlaceholder: "Internal notes about this bug report...",
        categories: {
            UI_DISPLAY: "UI / Display Issue",
            NAVIGATION: "Navigation Problem",
            DATA_ISSUE: "Data Inaccuracy",
            PERFORMANCE: "Slow Performance",
            AUTHENTICATION: "Login / Authentication",
            REPORT_SUBMISSION: "Report Submission",
            NOTIFICATION: "Notification Issue",
            OTHER: "Other",
        },
        statuses: {
            OPEN: "Open",
            IN_PROGRESS: "In Progress",
            RESOLVED: "Resolved",
            CLOSED: "Closed",
        },
        emptyState: {
            title: "No Bug Reports",
            description: "No bug reports have been submitted yet.",
        },
        updateSuccess: "Bug report updated.",
    },
    /* ── Settings ───────────────────────────────────────────────────────── */
    settings: {
        pageTitle: "App Settings",
        appearanceSection: "Appearance",
        themeLabel: "Theme",
        themeDescription: "Choose how the app looks to you.",
        themeSystem: "System default",
        themeLight: "Light",
        themeDark: "Dark",
        notificationsSection: "Notification Preferences",
        emailNotificationsLabel: "Email Notifications",
        emailNotificationsDescription: "Receive report deadline and status updates via email.",
        inAppNotificationsLabel: "In-App Notifications",
        inAppNotificationsDescription: "Show notification badge and pop-ups in the app.",
        deadlineRemindersLabel: "Deadline Reminders",
        deadlineRemindersDescription: "Get reminders 24 h and 48 h before report deadlines.",
        pushNotificationsSection: "Push Notifications",
        pushNotificationsLabel: "Push Notifications",
        pushNotificationsDescription: "Receive real-time push notifications on this device.",
        pushEnabled: "Push notifications enabled.",
        pushDisabled: "Push notifications disabled.",
        pushNotSupported: "Push notifications are not supported in this browser.",
        pushPermissionDenied: "Permission denied. Enable notifications in your browser settings.",
        pushNotConfigured: "Push notifications are not configured for this environment.",
        enablePush: "Enable Push",
        disablePush: "Disable Push",
        saved: "Preferences saved.",
        savePreferences: "Save Preferences",
        unsavedChanges: "Unsaved changes",
    },
    /* ── Offline Page ────────────────────────────────────────────────────────── */
    offline: {
        title: "You're Offline",
        description: "It looks like you've lost your internet connection. Check your connection and try again.",
        retryButton: "Try Again",
        hint: "Previously viewed pages may still be accessible from cache.",
    },

    /* ── Error Pages ─────────────────────────────────────────────────────── */
    errors: {
        generic: "Something went wrong. Please try again.",
        notFoundTitle: "Page Not Found",
        notFoundDescription: "The page you are looking for does not exist.",
        notFoundCta: "Go to Dashboard",
        bugReportCta: "Report Bug",
        errorTitle: "Something Went Wrong",
        errorDescription: "An unexpected error occurred. Consider refreshing or filing a bug report.",
        errorCta: "Try Again",
        offlineTitle: "You're Offline",
        offlineDescription: "Check your internet connection and try again.",
        onlineTitle: "You're Back Online",
        onlineDescription: "Connection restored.",
        previewFailed: "Preview failed",
        generationFailed: "Generation failed",
    },

    /* ── Landing page (root /) ─────────────────────────────────────────────── */
    landing: {
        hero: {
            eyebrow: "Harvesters Reporting System",
            headline: "Every campus report, in one auditable, analytics-ready place.",
            subheadline:
                "Standardise weekly + monthly reporting across campuses and groups. Run review workflows, roll up to group / org level, and surface the insights leadership actually needs.",
            primaryCtaGuestLabel: "Sign in",
            primaryCtaGuestHref: "/login",
            primaryCtaAuthLabel: "Open my dashboard",
            secondaryCtaLabel: "How it works",
            secondaryCtaHref: "/how-it-works",
        },
        features: [
            {
                title: "One place for every report",
                body: "Weekly and monthly numbers from every campus, every group, in one auditable place. No more tracking down spreadsheets, screenshots, or chat threads to know what's been submitted.",
            },
            {
                title: "Easy data entry for ushers",
                body: "Service-day data entry that flows straight into the weekly campus report. Ushers see only the numbers they're responsible for; auto-totals add things up so nothing has to be re-typed.",
            },
            {
                title: "Roll up the way leadership thinks",
                body: "See monthly, quarterly, and yearly views for any campus, group, or the whole organisation — one click from any report. The platform follows your org chart, however you've defined it.",
            },
            {
                title: "Insights you can act on",
                body: "See which numbers move together, which campuses are growing fastest, and where attention is needed most — without crunching the data yourself.",
            },
            {
                title: "Bring in spreadsheets you already use",
                body: "Upload an Excel or CSV file, point each column at the right metric, preview the result, and import. Multi-sheet workbooks prompt you to pick a sheet; bad files explain themselves instead of failing silently.",
            },
            {
                title: "Edit copy and structure without a developer",
                body: "Roles, hierarchy, dashboards, email templates, cadence, and the public pages — all editable through Admin Config. Add a new role, rename a level, or rewrite this very page without waiting for a release.",
            },
            {
                title: "Safe by default",
                body: "Every change is logged and reversible. Previewing the platform as another role keeps every action attributed back to you. Updates never overwrite the data already in your account.",
            },
            {
                title: "Works when the internet doesn't",
                body: "Drafts save locally and sync the moment you're back online. Email and push notifications are optional and stay quietly out of the way when they're not set up.",
            },
        ],
        quickLinksHeading: "Jump in",
        quickLinks: {
            authenticated: [
                { label: "Dashboard", href: "/dashboard" },
                { label: "Reports", href: "/reports" },
                { label: "Analytics", href: "/analytics" },
                { label: "How it works", href: "/how-it-works" },
            ],
            guest: [
                { label: "Sign in", href: "/login" },
                { label: "Have an invite?", href: "/join" },
                { label: "How it works", href: "/how-it-works" },
                { label: "About", href: "/about" },
            ],
        },
        welcomeBack: "Welcome back",
        signedOutBadge: "Not signed in",
        learnMore: "Learn more",
    },

    /* ── How It Works page ──────────────────────────────────────────────────── */
    howItWorks: {
        pageTitle: "How it works",
        pageSubtitle:
            "Short walkthroughs for every role, plus answers to common questions and small interactive demos you can try right on the page.",
        intro:
            "Pick a tab below to see what your role looks like day-to-day. Each tab includes a short walkthrough, a few frequently-asked questions, and a hands-on demo where it's helpful.",
        tabs: [
            {
                slug: "overview",
                title: "Overview",
                sections: [
                    {
                        heading: "What this platform is for",
                        body:
                            "Harvesters Reporting brings every campus report, review, approval, and analytics view into one place. No more scattered spreadsheets, screenshots, or chat threads. Every number can be traced to who entered it and when.",
                    },
                    {
                        heading: "How the roles fit together",
                        body:
                            "Ushers enter the service-day numbers through a simple form. Campus admins finish the weekly or monthly report and submit it. Group admins and pastors review and approve. CEO, SPO, and Church Ministry see organisation-wide views with one-click drill-downs.",
                    },
                    {
                        heading: "What admins can change without a developer",
                        body:
                            "Role names and what each role can do, your organisation's hierarchy, dashboard layouts, the wording in outbound emails, how often each role reports, and even the public pages on this site — all editable inside Admin Config. Changes show up the next time someone loads the page.",
                    },
                ],
                faqs: [
                    {
                        q: "Do I need to be online to fill a report?",
                        a: "No. Your drafts save in the browser and sync the moment you're back online. A small indicator in the corner shows when something is queued.",
                    },
                    {
                        q: "What happens if I lose access while editing?",
                        a: "Your draft survives. Sign back in and the form will be exactly where you left it.",
                    },
                ],
                playgroundIds: ["analytics-chart-toggle"],
            },
            {
                slug: "ushers",
                title: "For Ushers",
                sections: [
                    {
                        heading: "What you'll see when you sign in",
                        body:
                            "When you log in you land on the Quick Form page. Each card is one assignment — just the few numbers your campus admin asked you to fill, with nothing extra to wade through. Type in your numbers and the platform saves every 30 seconds. Tap Submit when you're done.",
                    },
                    {
                        heading: "Who decides which numbers you fill?",
                        body:
                            "A campus or group admin sets that up in advance from the template editor. They pick the specific numbers ushers are responsible for and how often (typically Sunday and Wednesday for service days). Once that's done, your form shows up automatically every period.",
                    },
                    {
                        heading: "Where what you enter goes",
                        body:
                            "Your numbers flow straight into the campus's weekly or monthly report — no copy-paste, no extra steps. Your campus admin sees a small badge next to each value so they know which numbers came from you.",
                    },
                ],
                faqs: [
                    {
                        q: "What if I'm asked for a number I don't have?",
                        a: "Leave it blank and save the draft. Your campus admin can follow up or fill it in themselves.",
                    },
                    {
                        q: "Can I change a value after I submit?",
                        a: "Yes, until your assignment is marked complete. After that, your campus admin handles changes.",
                    },
                ],
                playgroundIds: ["quick-form-demo"],
            },
            {
                slug: "campus-admin",
                title: "For Campus Admins",
                sections: [
                    {
                        heading: "Filling the campus report",
                        body:
                            "Open Reports → New report. The title and period fill in for you based on the template you pick. Anything your ushers have already submitted is sitting in the right cells. Fill in the rest, preview the totals, and submit when you're ready.",
                    },
                    {
                        heading: "Quick rollups from any report",
                        body:
                            "On any report detail page you'll see Monthly, Quarterly, and Yearly chips. One click takes you to a combined view of every report from your campus for that period — no extra setup, no configuration.",
                    },
                    {
                        heading: "Numbers that add themselves up",
                        body:
                            "If your template has a total metric (for example, Total attendance = Men + Women + Children), the platform fills it in automatically and locks the cell. The total updates every time a source value changes, with a small note showing which metrics it added together.",
                    },
                ],
                faqs: [
                    {
                        q: "Can I change a number an usher already filled?",
                        a: "Yes, until the report is approved. After approval, ask your campus pastor for an unlock.",
                    },
                ],
                playgroundIds: ["template-builder-effect", "auto-sum-chain"],
            },
            {
                slug: "group-leadership",
                title: "For Group Admins / Pastors",
                sections: [
                    {
                        heading: "What your dashboard shows",
                        body:
                            "You land on a group-wide view: how each campus is performing, which ones are growing fastest, who's behind on submissions, and a period selector to compare timeframes. Drill into any campus's reports without leaving the page.",
                    },
                    {
                        heading: "Reviewing and approving",
                        body:
                            "When campus admins submit, the reports queue under Pending review. Mark them Reviewed when the numbers look right; if something's off, request edits with a short reason and the campus admin gets a notification (and an email if email is set up).",
                    },
                ],
                faqs: [
                    {
                        q: "How do I see a quarter or year combined?",
                        a: "From any campus report detail page, click the Quarterly or Yearly chip. The combined view is calculated live from every report in the period.",
                    },
                ],
                playgroundIds: ["aggregation-rollup"],
            },
            {
                slug: "executive",
                title: "For CEO / SPO / Office of CEO / Church Ministry",
                sections: [
                    {
                        heading: "An organisation-wide picture",
                        body:
                            "Your dashboard shows how each group is doing, which campus is leading, the overall reporting rate, recent submissions, what's waiting on review, and quick links to the admin tools you use most. A superadmin can rearrange the cards from Admin Config → Dashboard layout.",
                    },
                    {
                        heading: "Insights, written for humans",
                        body:
                            "Each cycle the platform highlights what changed: who's grown the most, where the biggest gaps are, and how compliance is trending. Numbers that move together get spotlighted as soon as there's enough data to draw a clean line.",
                    },
                ],
                faqs: [
                    {
                        q: "Can I preview the platform as another role?",
                        a: "Yes — a superadmin can start a time-limited preview session. It's read-only by default so you can walk through screens safely; switch to mutate mode if you actually need to take action. Every step is logged so the trail still leads back to you.",
                    },
                ],
                playgroundIds: ["insight-summary-preview", "correlation-matrix-builder"],
            },
            {
                slug: "admin-config",
                title: "For Superadmin",
                sections: [
                    {
                        heading: "What lives in Admin Config",
                        body:
                            "Everything admins can change without a developer: roles and what each one can do, your organisation's hierarchy, dashboard layouts, email wording, how often each role reports, install prompts, invite defaults, and the public pages on this site. Saved changes show up the next time someone loads the affected page.",
                    },
                    {
                        heading: "Templates",
                        body:
                            "Templates → Sections & metrics defines what the report looks like. Templates → Quick-form assignments lets you pin specific metrics to specific roles (so ushers, for example, only see their few cells). Section-level auto-totals and correlation groups have their own panels — same shape, sitting one above the other.",
                    },
                    {
                        heading: "Previewing the platform as another role",
                        body:
                            "From the user menu, click Preview as another role. Pick the role; for roles tied to a campus or group, pick a real user too so the preview inherits their context. Sessions expire automatically (30 min by default) and every step is logged.",
                    },
                ],
                faqs: [
                    {
                        q: "How do I undo a bad change in Admin Config?",
                        a: "Every tab has a Reset to defaults button — it removes your override and restores the platform's built-in values for that section.",
                    },
                    {
                        q: "Can I add new roles at runtime?",
                        a: "Yes. The Roles tab has a New role button — give it a name, choose what it can do, optionally pin it to specific units, and save. Built-in roles stay marked as such; superadmin remains protected. Custom roles can be archived later without a release.",
                    },
                    {
                        q: "Can the org chart have more than one branch?",
                        a: "Yes. The Hierarchy tab supports multiple parallel trees side-by-side (for example, your usual Groups → Campuses tree alongside a Departments tree). Existing campuses and groups stay where they are; the new tree editor lets you add levels at any depth.",
                    },
                    {
                        q: "What if some old data hasn't moved to the new structure yet?",
                        a: "Click Reconcile in the Hierarchy tab to migrate any older data into the new structure. It's safe to run any time — it never overwrites data you've already entered.",
                    },
                    {
                        q: "Imports keeps erroring on .xlsx — is that fixed?",
                        a: "Yes. The wizard now accepts .csv, .xlsx, and .xls. Workbooks with multiple sheets ask you to pick one; bad files explain themselves with a clear message instead of failing silently.",
                    },
                ],
                playgroundIds: ["correlation-demo", "import-wizard-demo"],
            },
        ],
        playgroundComingSoon: "Hands-on playground — coming soon for this section.",
        relatedHelpHeading: "Related help",
    },

    /* ── About / Privacy / Terms (admin-editable, hardcoded fallbacks) ───────
     *
     * Each page has a `title`, optional `subtitle`, and a `sections[]` array of
     * heading + body blocks. Admins edit these through Admin Config; the
     * platform always falls back to the values here when no DB override exists,
     * so public pages never render blank.
     */
    aboutPage: {
        title: "About Harvesters Reporting",
        subtitle: "What this platform is, who built it, and why it exists.",
        sections: [
            {
                heading: "What this platform is",
                body:
                    "Harvesters Reporting brings every campus report, review, approval, and analytics view into one place for Harvesters International Christian Centre. It replaces a tangle of spreadsheets, screenshots, and chat messages with a single, traceable home for the numbers leadership relies on.",
            },
            {
                heading: "What we believe",
                body:
                    "Numbers should be honest, every value should be traceable to who entered it, and admins shouldn't need a developer to change wording or workflow. Roles, hierarchy, dashboards, email wording, and the public pages on this site can all be edited inside Admin Config — the change shows up the next time someone loads the page.",
            },
            {
                heading: "Who built it",
                body:
                    "Built and maintained by HICC's reporting team in collaboration with S.D. Use the bug-report link in the app to send us feedback or report something that needs attention.",
            },
        ],
    },
    privacyPage: {
        title: "Privacy",
        subtitle: "How we handle the data you put into the platform.",
        sections: [
            {
                heading: "What we collect",
                body:
                    "Only what you submit through the platform: the report values you enter, the goals you set, your profile information, any bug reports you send, and the screenshots you attach. We don't run third-party trackers and we don't sell or share your data with advertisers.",
            },
            {
                heading: "Where it's stored",
                body:
                    "Your data lives in a database operated under HICC's control. Screenshots you attach to bug reports are stored with a trusted hosting provider and are removed when the linked report is deleted.",
            },
            {
                heading: "Email handling",
                body:
                    "Outbound email (verification, invites, review notices, reset links) is sent through a trusted email provider when one is set up. If email isn't configured, the platform still works — these messages show up inside the app instead, and nothing else changes.",
            },
            {
                heading: "Audit and previews",
                body:
                    "Every meaningful action (creating, submitting, approving, locking, unlocking, editing) is recorded against the person who did it. When a superadmin previews the platform as another role, the session is time-limited and every step is logged so the trail still leads back to the real actor.",
            },
            {
                heading: "Your rights",
                body:
                    "You can ask your campus admin or the team (via the bug-report flow) to export or remove your profile information. Report content itself is an organisational record and is kept in line with HICC's policy.",
            },
        ],
    },
    termsPage: {
        title: "Terms of Use",
        subtitle: "House rules for using the platform.",
        sections: [
            {
                heading: "Who can use the platform",
                body:
                    "The platform is for invited HICC members, staff, leadership, and authorised partners. Accounts are personal — please don't share your password. Forgotten passwords can be reset from the sign-in page or by your campus admin.",
            },
            {
                heading: "What we ask of you",
                body:
                    "Please submit reports honestly and on time, only enter data you're responsible for, and don't try to work around your role's permissions. Don't upload anything offensive or unlawful. If something looks broken, send us a bug report through the link in the app.",
            },
            {
                heading: "What we provide",
                body:
                    "We do our best to keep the platform up, current, and secure. Planned maintenance is announced inside the app. Your drafts save in the browser so a brief connection blip never costs you the work you've already typed.",
            },
            {
                heading: "Changes to these terms",
                body:
                    "These terms may be updated as the platform evolves. We announce meaningful changes inside the app; continuing to use the platform after a notice means you accept the updated terms.",
            },
        ],
    },

    /* ── Need Help? anchor + page → tab map ────────────────────────────────── */
    helpAnchors: {
        "/dashboard": "overview",
        "/reports": "campus-admin",
        "/reports/new": "campus-admin",
        "/reports/aggregate": "group-leadership",
        "/quick-form": "ushers",
        "/templates": "admin-config",
        "/admin-config": "admin-config",
        "/analytics": "executive",
        "/users": "admin-config",
        "/invites": "admin-config",
        "/imports": "admin-config",
    },
    helpLinkLabel: "Need help?",
    helpLinkAria: "Open help for this page",

    /* ── Impersonation (superadmin role preview) ──────────────────────────── */
    impersonation: {
        bannerReadOnlyTitle: "Previewing as",
        bannerReadOnlyHint: "Read-only — actions will not apply.",
        bannerMutateTitle: "Previewing & MUTATING as",
        bannerMutateHint: "Mutate mode — changes take real effect.",
        bannerExpiresIn: "Expires in",
        bannerForUser: "for",
        modeReadOnlyLabel: "Read only",
        modeMutateLabel: "Mutate",
        switchToMutate: "Switch to mutate",
        switchToReadOnly: "Switch to read-only",
        exit: "Exit preview",
        exiting: "Exiting…",
        startTitle: "Preview the app as another role",
        startSubtitle:
            "Time-limited preview. Your SUPERADMIN identity stays the actor of record; every action is audit-tagged.",
        startSubmit: "Start preview",
        startCancel: "Cancel",
        roleLabel: "Role",
        userLabel: "Specific user (optional)",
        userLabelRequired: "Specific user (required for campus/group-scoped roles)",
        targetRequired:
            "This role is scoped to a campus or group — pick a real user so the preview inherits their scope. Without a target the preview can't materialise their assignments.",
        previewNoCampusBanner:
            "You're previewing this scoped role without a target user, so there's no campus context to materialise assignments against. Exit and start over with a target user picked.",
        modeLabel: "Mode",
        readOnlyDescription:
            "Walk flows safely. Mutating endpoints will return 403 and be logged as blocked.",
        mutateDescription:
            "Actions take real effect on production data. Audit rows are tagged with your impersonation context.",
        toasts: {
            started: "Preview started.",
            stopped: "Preview ended.",
            modeSwitched: "Mode switched.",
            mutationBlocked:
                "Read-only preview — switch to mutate mode to apply changes, or exit preview.",
            startFailed: "Could not start preview.",
        },
        rowActionLabel: "Preview as this user",
        managePageTitle: "Impersonation log",
        managePageSubtitle: "Past sessions and per-event timeline.",
        eventTypeLabels: {
            STARTED: "Started",
            STOPPED: "Stopped",
            MODE_CHANGED: "Mode changed",
            MUTATION_BLOCKED: "Mutation blocked",
            MUTATION_APPLIED: "Mutation applied",
            PAGE_VISITED: "Page visited",
            AUTH_REJECTED: "Auth rejected",
            EVENT_LIMIT_REACHED: "Event limit reached",
        },
    },

    /* ── Report quick views (aggregated rollup CTAs) ──────────────────────── */
    reportsQuickViews: {
        heading: "Aggregated views",
        regionLabel: "Aggregated report quick views",
        noDataTooltip: "No source data yet for this rollup",
    },

    /* ── Users list ──────────────────────────────────────────────────────────── */
    usersList: {
        statusLabels: {
            ACTIVE: "Active",
            INACTIVE: "Inactive",
            ACTIVATION_PENDING: "Awaiting activation",
            PENDING_INVITE: "Invited",
        },
        statusColors: {
            ACTIVE: "green",
            INACTIVE: "default",
            ACTIVATION_PENDING: "blue",
            PENDING_INVITE: "orange",
        },
        filterAll: "All",
        showInvited: "Show invited & pre-registered",
        directoryHint: "Includes invited and pre-registered users alongside active accounts.",
    },

    /* ── Admin Config ────────────────────────────────────────────────────────── */
    adminConfig: {
        pageTitle: "Admin Config",
        subtitle: "Edit roles, hierarchy, dashboards, email wording, and the public pages — without a developer.",
        namespaceLabels: {
            roles: "Roles & Capabilities",
            hierarchy: "Hierarchy & Org Units",
            dashboardLayout: "Dashboard Layout",
            templatesMapping: "Template & Metric Mappings",
            imports: "Import Defaults",
            pwaInstall: "PWA Install Copy",
            bulkInvites: "Invite Defaults",
            analytics: "Analytics Defaults",
            emailTemplates: "Email Templates",
            roleCadence: "Role Cadence",
            correlation: "Insights & Correlation",
            landing: "Landing Page Copy",
            howItWorks: "How It Works Copy",
            aboutPage: "About Page",
            privacyPage: "Privacy Page",
            termsPage: "Terms Page",
            impersonationLog: "Impersonation log",
        },
        actions: {
            save: "Save namespace",
            reset: "Reset to defaults",
            diff: "Show diff vs fallback",
        },
        toasts: {
            saved: "Configuration saved.",
            reset: "Reverted to defaults.",
            conflict: "Someone else updated this namespace. Reload and re-apply.",
            saveFailed: "Could not save configuration. Try again.",
        },
        labels: {
            currentVersion: "Current version",
            usingFallback: "Using built-in defaults",
            usingDbOverride: "Using database override",
            updatedBy: "Updated by",
            namespace: "Namespace",
        },
        emptyState: {
            title: "No overrides yet",
            description: "This namespace is currently served from the built-in defaults. Save changes here to take over.",
        },
    },

    /* ── Imports ─────────────────────────────────────────────────────────────── */
    imports: {
        pageTitle: "Spreadsheet Imports",
        subtitle: "Bring CSV/XLSX data into reports with mapped columns and a safe preview.",
        steps: {
            upload: "Upload",
            map: "Map columns",
            preview: "Preview",
            commit: "Commit",
        },
        actions: {
            uploadFile: "Choose file",
            saveMapping: "Save mapping profile",
            useSavedMapping: "Use saved mapping",
            validate: "Validate",
            commit: "Commit import",
            cancel: "Cancel job",
        },
        toasts: {
            jobCreated: "Import job created.",
            mappingSaved: "Mapping saved.",
            validated: "Validation complete.",
            committed: "Import committed.",
            failed: "Import failed.",
            cancelled: "Import cancelled.",
        },
        emptyState: {
            title: "No active imports",
            description: "Upload a spreadsheet to start a new import job.",
        },
        outcomeLabels: {
            OK: "Ready",
            WARNING: "Warning",
            ERROR: "Error",
            COMMITTED: "Committed",
        },
    },

    /* ── Quick Form (Usher / Data Entry) ───────────────────────────────────── */
    quickForm: {
        pageTitle: "My Assignments",
        subtitle: "Fill in the metric values you have been assigned.",
        fillTitle: "Quick Fill",
        fillSubtitle: "Enter values for assigned metrics only.",
        emptyState: {
            title: "No active assignments",
            description: "When someone assigns you a form, it will appear here.",
        },
        statusLabels: {
            active: "Active",
            completed: "Completed",
            cancelled: "Cancelled",
            overdue: "Overdue",
        },
        actions: {
            startFill: "Start filling",
            saveDraft: "Save draft",
            submit: "Submit values",
        },
        autosave: {
            saving: "Saving…",
            saved: "Draft saved",
            failed: "Could not save draft",
        },
    },

    /* ── PWA Install Banner ─────────────────────────────────────────────────── */
    pwaInstall: {
        bannerTitle: "Install the Harvesters Reporting app",
        bannerSubtitle: "Get one-tap access, faster load, and offline drafts. Install in under a minute.",
        installCta: "Install",
        snoozeCta: "Maybe later",
        neverCta: "Don't show again",
        platformInstructions: {
            IOS: "Tap the Share icon in Safari, then choose “Add to Home Screen”.",
            ANDROID: "Tap the menu (⋮) in Chrome, then choose “Install app”.",
            DESKTOP: "Use the install icon in your address bar (Chrome, Edge) or the browser menu.",
        },
        push: {
            title: "Enable notifications",
            subtitle: "Get instant pings for approvals, deadlines, and assignments.",
            enableCta: "Enable",
            laterCta: "Maybe later",
            blockedHelp: "Notifications are blocked in your browser settings. Allow them and try again.",
        },
    },

    /* ── Bulk Invites + Pre-register + Activation ──────────────────────────── */
    bulkInvites: {
        pageTitle: "Bulk Invites",
        subtitle: "Create many invite links in one go.",
        modes: {
            link: "Generate invite links",
            preregister: "Pre-register users",
        },
        actions: {
            addRow: "Add another",
            paste: "Paste from clipboard",
            send: "Send invites",
            preregister: "Create activation links",
            downloadCsv: "Download outcomes (CSV)",
        },
        outcomeLabels: {
            created: "Invite created",
            already_invited: "Already invited",
            already_registered: "Already registered",
            failed: "Failed",
            preregistered: "Activation sent",
            activation_skipped: "User already active",
        },
        emptyState: {
            title: "No bulk batches yet",
            description: "Add rows above to create your first bulk invite or pre-register batch.",
        },
        helpers: {
            sharedDefaults: "Shared defaults are used unless a row overrides them.",
            csvHint: "Paste rows as: email, role, campus|group (one per line).",
        },
    },

    preregister: {
        emailSubject: "Activate your Harvesters Reporting account",
        emailIntro: "Your account has been pre-created. Click below to set your password and sign in.",
        actionLabel: "Activate account",
        expiryNote: "This link will expire in",
    },

    activation: {
        pageTitle: "Activate your account",
        subtitle: "Set a new password to finish activating.",
        invalidTitle: "Activation link invalid or expired",
        invalidDescription: "Ask your admin to send a new activation link.",
        successTitle: "Account activated",
        successDescription: "You can now sign in with your new password.",
        actionSubmit: "Activate and sign in",
    },

    /* ── SEO / Meta ──────────────────────────────────────────────────────────── */
    seo: {
        appDescription: "The central report management platform for Harvesters International Christian Centre — campus report submission, review, and analytics.",
        // Auth pages
        loginDescription: "Sign in to the Harvesters Reporting System to access your campus reports and analytics.",
        registerDescription: "Create your Harvesters Reporting System account to start managing campus reports.",
        forgotPasswordDescription: "Reset your Harvesters Reporting System password.",
        resetPasswordDescription: "Set a new password for your Harvesters Reporting System account.",
        joinTitle: "You're Invited",
        joinDescription: "You have been invited to join the Harvesters Reporting System — the central platform for campus report submission and analytics at Harvesters International Christian Centre.",
        // Dashboard pages
        dashboardDescription: "View your reporting dashboard — KPIs, recent activity, and upcoming deadlines.",
        reportsDescription: "Manage, submit, and review campus reports across Harvesters campuses.",
        newReportDescription: "Create and submit a new campus report.",
        reportDetailDescription: "View the full details and history of this campus report.",
        reportEditDescription: "Edit and update this campus report.",
        templatesDescription: "Manage report templates used across campuses for standardised data collection.",
        newTemplateDescription: "Create a new report template to standardise campus reporting.",
        templateDetailDescription: "View and manage this report template.",
        usersDescription: "Manage system users — roles, campus assignments, and access levels.",
        userDetailDescription: "View and manage this user's profile and role assignment.",
        orgDescription: "Manage the organisation hierarchy — groups, campuses, and zones.",
        analyticsDescription: "Analyse report data, trends, and compliance metrics across all campuses.",
        inboxDescription: "Stay up to date with report approvals, edit requests, and system notifications.",
        goalsDescription: "Set and track performance goals to measure campus progress against targets.",
        invitesDescription: "Generate and manage invite links to onboard new users to the system.",
        bugReportsDescription: "Report a bug or issue you encountered in the Harvesters Reporting System.",
        bugReportsManageDescription: "Review and manage all bug reports submitted by system users.",
        profileDescription: "Manage your profile, security settings, and notification preferences.",
    },
} satisfies AppContent;

export type ContentKey = typeof CONTENT;
