/**
 * config/content.ts
 * Every user-visible string lives here.
 * Components import CONTENT and reference by key — zero string literals in JSX.
 */

// AppContent is declared in types/global.d.ts inside `declare global` — no import needed.

export const CONTENT = {
    /* ── Navigation ──────────────────────────────────────────────────────── */
    nav: {
        dashboard: "Dashboard",
        reports: "Reports",
        aggregatedReports: "Aggregated Reports",
        templates: "Templates",
        analytics: "Analytics",
        users: "Users",
        org: "Organisation",
        inbox: "Inbox",
        invites: "Invite Links",
        settings: "Settings",
        goals: "Goals",
        bugReports: "Report a Bug",
        bugReportsManage: "Bug Reports",
        profile: "Profile",
        logout: "Logout",
        backToDashboard: "Back to Dashboard",
        quickForm: "Quick Form",
        imports: "Imports",
        bulkInvites: "Bulk Invites",
        adminConfig: "Admin Config",
    },

    /* ── Auth ─────────────────────────────────────────────────────────────── */
    auth: {
        loginTitle: "Sign In",
        loginSubtitle: "Welcome back to the Harvesters Reporting System",
        emailLabel: "Email Address",
        emailPlaceholder: "you@harvestersng.org",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter your password",
        loginButton: "Sign In",
        loggingIn: "Signing in…",
        forgotPassword: "Forgot password?",
        noAccount: "Don't have an account?",
        registerLink: "Create an account",
        registerTitle: "Create Account",
        registerSubtitle: "Set up your Harvesters Reporting System account",
        firstNameLabel: "First Name",
        lastNameLabel: "Last Name",
        firstNamePlaceholder: "Your first name",
        lastNamePlaceholder: "Your last name",
        phoneLabel: "Phone Number",
        phonePlaceholder: "+234 800 000 0000",
        registerButton: "Create Account",
        alreadyHaveAccount: "Already have an account?",
        loginLink: "Sign in",
        forgotTitle: "Reset Password",
        forgotSubtitle: "Enter your email and we'll send reset instructions",
        sendResetLink: "Send Reset Link",
        resetTitle: "Set New Password",
        resetSubtitle: "Choose a strong new password",
        newPasswordLabel: "New Password",
        confirmPasswordLabel: "Confirm Password",
        resetButton: "Reset Password",
        joinTitle: "Join via Invite",
        joinSubtitle: "Complete your registration using an invite link",
        errors: {
            invalidCredentials: "Invalid email or password.",
            serverError: "Something went wrong. Please try again.",
            emailRequired: "Email is required.",
            emailInvalid: "Please enter a valid email address.",
            passwordRequired: "Password is required.",
            passwordsDoNotMatch: "Passwords do not match.",
            passwordTooShort: "Password must be at least 8 characters.",
            invalidToken: "This invite link is invalid or has expired.",
        },
        accountInfoLabel: "Account Information",
        passwordChangedSuccess: "Password changed successfully.",
        currentPasswordLabel: "Current Password",
        changePasswordAction: "Change Password",
        profileTabLabel: "Profile",
        passwordTabLabel: "Password",
        inviteInvalidTitle: "Invalid Invite Link",
        inviteExpiredTitle: "Invite Link Expired",
        inviteUsedTitle: "Invite Already Used",
        goToLogin: "Go to Login",
        registrationSuccessTitle: "Registration Successful",
        registrationSuccessMessage: "Your account has been created. You can now sign in.",
        redirectingIn: "Redirecting to login in",
        inviteRoleLabel: "You have been invited as",
        rememberMe: "Remember me",
        haveInvite: "Have an invite link?",
        joinWithInvite: "Join with invite",
        noInvite: "No invite link?",
        registerWithoutInvite: "Create a free account",
    },

    /* ── Reports ────────────────────────────────────────────────────────── */
    reports: {
        pageTitle: "Reports",
        newReport: "New Report",
        submitReport: "Submit Report",
        saveDraft: "Save Draft",
        requestEdit: "Request Edit",
        approveReport: "Approve",
        markReviewed: "Mark Reviewed",
        lockReport: "Lock Report",
        viewReport: "View Report",
        editReport: "Edit Report",
        viewHistory: "View History",
        requestUpdate: "Request Update",
        filterByStatus: "Filter by status",
        filterByCampus: "Filter by campus",
        filterByPeriod: "Filter by period",
        filterByTemplate: "Filter by template",
        searchPlaceholder: "Search reports…",
        periodLabel: "Period",
        statusLabel: "Status",
        campusLabel: "Campus",
        groupLabel: "Group",
        deadlineLabel: "Deadline",
        submittedByLabel: "Submitted By",
        submittedAtLabel: "Submitted At",
        reviewedByLabel: "Reviewed By",
        approvedByLabel: "Approved By",
        lockedAtLabel: "Locked At",
        notesLabel: "Notes",
        notesPlaceholder: "Add any notes or context…",
        dataEntryBadge: "Data Entry",
        fieldGoal: "Goal",
        fieldAchieved: "Achieved",
        fieldYoY: "YoY Goal",
        fieldGoalComment: "Add goal comment",
        fieldAchievedComment: "Add context",
        fieldYoYComment: "Add YoY comment",
        metricComment: "Add comment",
        commentPlaceholder: "Optional context or note…",
        goalPrefilledTooltip: "Pre-filled from set goals — not editable while filling a report",
        goalFromSource: "Goal source",
        goalNotSet: "No goal set",
        goalLocked: "Goal locked",
        goalsLoading: "Loading goals…",
        goalsPrefilledBadge: "goals pre-filled",
        noGoalsSet: "No goals set for this period — enter values manually",
        statVsGoal: "vs Goal",
        statVsYoY: "vs Last Year",
        requiredFilled: "required filled",
        liveStats: "Live Statistics",
        statOverallGoal: "Overall Goal Progress",
        statYoYGrowth: "Year-on-Year Growth",
        statMetricsWithGoal: "Metrics with Goals",
        metricsFormTitle: "Report Data",
        sectionRequired: "Required",
        sectionOptional: "Optional",
        emptyState: {
            title: "No Reports Found",
            description: "No reports match your current filters.",
            newReportCta: "Submit your first report",
        },
        deleteConfirm: "Are you sure you want to delete this report?",
        submitConfirm: "Submit this report for review?",
        approveConfirm: "Approve this report?",
        lockConfirm: "Lock this report? This cannot be undone.",
        editRequestTitle: "Request Edit",
        editRequestReasonLabel: "Reason for Edit",
        editRequestReasonPlaceholder: "Describe what needs to be corrected…",
        editRequestSubmit: "Submit Edit Request",
        updateRequestTitle: "Request Update",
        updateReasonLabel: "Reason for Update",
        updateReasonPlaceholder: "Explain why this update is needed…",
        updateRequestSubmit: "Submit Update Request",
        editRequestDraftTitle: "Draft Edit",
        editRequestApprove: "Approve Edit",
        editRequestReject: "Reject Edit",
        historyTitle: "Report History",
        auditTrailTitle: "Audit Trail",
        eventLabels: {
            CREATED: "Report Created",
            SUBMITTED: "Report Submitted",
            EDIT_REQUESTED: "Edits Requested",
            EDIT_SUBMITTED: "Edit Submitted",
            EDIT_APPROVED: "Edit Approved",
            EDIT_REJECTED: "Edit Rejected",
            EDIT_APPLIED: "Edit Applied",
            TRANSLATED: "Translated",
            APPROVED: "Report Approved",
            REVIEWED: "Report Reviewed",
            LOCKED: "Report Locked",
            UNLOCKED: "Report Unlocked",
            DEADLINE_PASSED: "Deadline Passed",
            UPDATE_REQUESTED: "Update Requested",
            UPDATE_APPROVED: "Update Approved",
            UPDATE_REJECTED: "Update Rejected",
            DATA_ENTRY_CREATED: "Data Entry Submitted",
            TEMPLATE_VERSION_NOTE: "Template Version Updated",
            AUTO_APPROVED: "Auto-Approved",
        },
        sections: {
            attendanceTitle: "Weekly Attendance",
            salvationsTitle: "Salvations & First Timers",
            discipleshipTitle: "Discipleship",
            tithesTitle: "Tithes & Offerings",
            workersTitle: "Workers",
            outreachTitle: "Outreach",
            youthTitle: "Youth",
            childrenTitle: "Children",
            mediaTitle: "Media & Digital",
            prayerTitle: "Prayer",
            infrastructureTitle: "Infrastructure & Facilities",
        },
        status: {
            DRAFT: "Draft",
            SUBMITTED: "Submitted",
            REQUIRES_EDITS: "Requires Edits",
            APPROVED: "Approved",
            REVIEWED: "Reviewed",
            LOCKED: "Locked",
        },
        actions: {
            submit: "Submit",
            approve: "Approve",
            review: "Mark Reviewed",
            lock: "Lock",
            unlock: "Unlock",
            requestEdit: "Request Edit",
        },
        columnLabels: {
            report: "Report",
            title: "Title",
            campus: "Campus",
            period: "Period",
            status: "Status",
            submittedBy: "Submitted By",
            submittedAt: "Submitted At",
            deadline: "Deadline",
            createdAt: "Created",
            lockedAt: "Locked At",
            actions: "",
        },
        filterLabels: {
            status: "Status",
            campus: "Campus",
            period: "Period",
            template: "Template",
            all: "All",
        },
        metadata: {
            title: "Details",
            templateLabel: "Template",
            periodTypeLabel: "Period Type",
            yearLabel: "Year",
            weekLabel: "Week",
            monthLabel: "Month",
            createdByLabel: "Created By",
            deadlineLabel: "Deadline",
            lockedAtLabel: "Locked At",
        },
        aggregation: {
            pageTitle: "Aggregated Reports",
            pageSubtitle: "Run rollup reporting by campus/group/yearly cycles",
            back: "Back",
            selectScopeStep: "1. Select scope",
            selectPeriodStep: "2. Select period",
            selectTemplateStep: "3. Select template + metrics",
            scopeCampus: "Campus",
            scopeGroup: "Group",
            scopeAll: "All",
            selectCampus: "Select campus",
            selectGroup: "Select group",
            pickMonth: "Pick month",
            pickWeek: "Pick week",
            pickYear: "Pick year",
            allMonths: "All months",
            allWeeks: "All weeks",
            sourceReportsTag: "Source reports",
            metricsTag: "Metrics",
            templatePlaceholder: "Template",
            metricsPlaceholder: "Metrics (optional)",
            statusesPlaceholder: "Statuses",
            includeDraftsLabel: "Include draft reports",
            includeDraftsHint: "Toggle to include/exclude drafts in rollup and benchmark.",
            previewButton: "Preview Aggregation",
            generateButton: "Generate Aggregated Report",
            exportButton: "Export Aggregated Report",
            exportGroupedDetailsToggle: "Include grouped source report details sheet",
            exportGroupedDetailsHint:
                "Adds an extra export sheet grouped by org group and campus, with section and metric rows aligned for each source report.",
            ungroupedLabel: "Ungrouped",
            previewTitle: "Aggregation Preview",
            reportsIncluded: "Reports included",
            templateTag: "Template",
            sectionsTag: "Sections",
            noTemplate: "N/A",
            loadingPreviewSuccess: "Preview loaded. Verify details before generating.",
            loadingPreviewError: "Failed to preview aggregation",
            previewRequiredWarning: "Please run preview first.",
            generatedSuccess: "Aggregated report created successfully.",
            generatedError: "Failed to generate report",
            exportMissingWarning: "No aggregation preview available for export.",
            accessDeniedTitle: "Access denied",
            accessDeniedDescription: "You are not permitted to use aggregation.",
            scopeRequiredError: "Please select a scope before previewing.",
            scopeLockedHint: "Scope is fixed by your role permissions.",
        },
        export: {
            button: "Export (.xlsx)",
            dialogTitle: "Export Reports",
            scopeLabel: "Export Scope",
            scopeAll: "All filtered reports",
            scopeSelected: "Selected reports only",
            groupingLabel: "Group by",
            groupingNone: "None",
            groupingCampus: "Campus",
            groupingMonth: "Month",
            groupingQuarter: "Quarter",
            contentLabel: "Include",
            contentMetrics: "Metric values",
            contentGoals: "Goal values",
            contentComments: "Comments",
            contentStatus: "Status history",
            formatLabel: "Format",
            formatSingleSheet: "Single sheet",
            formatMultiSheet: "One sheet per campus",
            exportButtonLabel: "Export",
            cancelButtonLabel: "Cancel",
            listFilename: "harvesters-reports",
            sheetList: "Reports",
            sheetMeta: "Overview",
            sheetMetrics: "Metrics",
            colTitle: "Title",
            colCampus: "Campus",
            colPeriod: "Period",
            colStatus: "Status",
            colTemplate: "Template",
            colDeadline: "Deadline",
            colCreatedAt: "Created",
            colSubmittedBy: "Submitted By",
            colNotes: "Notes",
            colSection: "Section",
            colMetric: "Metric",
            colAchieved: "Achieved",
            colGoal: "Goal",
            colPercentage: "% of Goal",
            colComment: "Comment",
        },
    },

    /* ── Templates ────────────────────────────────────────────────────────── */
    templates: {
        pageTitle: "Report Templates",
        newTemplate: "New Template",
        editTemplate: "Edit Template",
        previewTemplate: "Preview",
        publishTemplate: "Publish",
        archiveTemplate: "Archive",
        setDefault: "Set as Default",
        versionsLabel: "Version History",
        goalPromptTitle: "Set Goals for This Template?",
        goalPromptDescription: "This template captures goals for some metrics. Setting goals now lets fillers see progress against targets in the report form.",
        goalPromptConfirm: "Set Goals Now",
        goalPromptSkip: "Set Goals Later",
        templateSaved: "Template saved.",
        templateCreated: "Template created.",
        nameLabel: "Template Name",
        namePlaceholder: "e.g. Standard Campus Weekly Report",
        descriptionLabel: "Description",
        descriptionPlaceholder: "Brief description of this template's purpose",
        addSection: "Add Section",
        addMetric: "Add Metric",
        removeSection: "Remove Section",
        sectionLabel: "Section",
        sectionsLabel: "Sections",
        sectionNameLabel: "Section Name",
        metricNameLabel: "Metric Name",
        fieldTypeLabel: "Field Type",
        calculationTypeLabel: "Calculation Method",
        isRequiredLabel: "Required",
        capturesGoalLabel: "Captures Goal",
        capturesAchievedLabel: "Captures Achieved",
        capturesYoYLabel: "Captures YoY Goal",
        defaultBadge: "Default",
        createTemplate: "Create Template",
        emptySections: "No sections yet. Click Add Section to start building this template.",
        emptyMetrics: "No metrics yet. Add a metric below.",
        emptyState: {
            title: "No Templates",
            description: "Create a report template to start collecting data.",
        },
    },

    /* ── Goals ─────────────────────────────────────────────────────────────── */
    goals: {
        pageTitle: "Goals",
        setGoal: "Set Goal",
        editGoal: "Edit Goal",
        requestUnlock: "Request Edit",
        approveUnlock: "Approve",
        rejectUnlock: "Reject",
        targetValueLabel: "Target Value",
        yearLabel: "Year",
        monthLabel: "Month",
        modeLabel: "Goal Mode",
        lockedBadge: "Locked",
        pendingUnlockBadge: "Unlock Pending",
        unlockReasonLabel: "Reason for Unlock",
        unlockReasonPlaceholder: "Explain why this goal needs to be changed\u2026",
        cancelEdit: "Cancel",
        modeAnnual: "Annual \u2014 same target each month",
        modeMonthly: "Monthly \u2014 set per month individually",
        campusLabel: "Campus",
        allCampuses: "All Campuses",
        annualTargetLabel: "Annual Target (applies to all 12 months)",
        saveGoals: "Save Goals",
        savedGoals: "Goals saved successfully.",
        templateLabel: "Template",
        months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        lockedNote: "Locked \u2014 submit an unlock request to change this goal",
        noTemplate: "No active template found. Create a template first.",
        saveAll: "Save All Goals",
        metricColumn: "Metric",
        annualTargetShort: "Target",
        bulkNote: "Set annual targets for all campuses in a single view.",
        noGoalSet: "—",
        emptyState: {
            title: "No Goals Set",
            description: "Goals help track expected performance against actuals.",
        },
    },

    /* ── Dashboard ────────────────────────────────────────────────────────── */
    dashboard: {
        pageTitle: "Dashboard",
        kpi: {
            totalReports: "Total Reports",
            pendingReview: "Pending Review",
            approvedReports: "Approved",
            complianceRate: "Compliance Rate",
            submittedOnTime: "On-Time Submissions",
            overdueReports: "Overdue",
            activeTemplates: "Active Templates",
            totalCampuses: "Total Campuses",
            totalUsers: "Total Users",
            drafts: "Drafts",
            requiresEdits: "Requires Edits",
            quarterlyCompliance: "Quarter Compliance",
        },
        welcomeBack: "Welcome back",
        recentActivity: "Recent Activity",
        noActivity: "No recent activity.",
        upcomingDeadlines: "Upcoming Deadlines",
        noDeadlines: "No upcoming deadlines.",
        cta: {
            pendingApproval: (n: number) => `There ${n === 1 ? "is" : "are"} ${n} report${n === 1 ? "" : "s"} pending approval`,
            pendingReview: (n: number) => `There ${n === 1 ? "is" : "are"} ${n} approved report${n === 1 ? "" : "s"} awaiting review sign-off`,
            draftReports: (n: number) => `You have ${n} draft report${n === 1 ? "" : "s"} in progress`,
            requiresEdits: (n: number) => `There ${n === 1 ? "is" : "are"} ${n} report${n === 1 ? "" : "s"} that require${n === 1 ? "s" : ""} edits`,
            weeklyReportDue: (period: string) => `You have a weekly report due for ${period}`,
            verifyEmail: (email: string) => `Please verify your email (${email}) to secure your account`,
            viewReports: "View Reports",
            openProfile: "Open Profile",
        },
        memberLobby: {
            title: "Welcome to Harvesters Reporting",
            subtitle: "Your account has been created successfully. An administrator will assign you a role to get started.",
            waitingLabel: "Awaiting role assignment",
            currentRole: "Current role",
            contactAdmin: "If you believe this is an error, please contact your campus administrator.",
        },
    },

    /* ── Users ───────────────────────────────────────────────────────────── */
    users: {
        pageTitle: "Users",
        inviteUser: "Invite User",
        editUser: "Edit User",
        deactivateUser: "Deactivate",
        activateUser: "Activate",
        resetPassword: "Reset Password",
        nameLabel: "Name",
        emailLabel: "Email",
        roleLabel: "Role",
        campusLabel: "Campus",
        groupLabel: "Group",
        statusLabel: "Status",
        activeStatus: "Active",
        inactiveStatus: "Inactive",
        searchPlaceholder: "Search users…",
        emptyState: {
            title: "No Users Found",
            description: "No users match your current filters.",
        },
        confirmDeactivate: "Deactivate this user? They will no longer be able to log in.",
        confirmActivate: "Reactivate this user?",
        roles: {
            SUPERADMIN: "Superadmin",
            SPO: "SPO",
            CEO: "CEO",
            OFFICE_OF_CEO: "Office of CEO",
            CHURCH_MINISTRY: "Church Ministry",
            GROUP_PASTOR: "Group Pastor",
            GROUP_ADMIN: "Group Admin",
            CAMPUS_PASTOR: "Campus Pastor",
            CAMPUS_ADMIN: "Campus Admin",
            DATA_ENTRY: "Data Entry",
            USHER: "Usher",
            MEMBER: "Member",
        },
        recentReports: "Recent Reports",
        noReports: "No reports submitted yet.",
    },

    /* ── Organisation ────────────────────────────────────────────────────── */
    org: {
        pageTitle: "Organisation",
        newGroup: "New Group",
        newCampus: "New Campus",
        editGroup: "Edit Group",
        editCampus: "Edit Campus",
        groupNameLabel: "Group Name",
        campusNameLabel: "Campus Name",
        countryLabel: "Country",
        locationLabel: "Location",
        leaderLabel: "Group Leader",
        adminLabel: "Campus Admin",
        campusesLabel: "Campuses",
        membersLabel: "Members",
        emptyStateGroups: {
            title: "No Groups",
            description: "Add an org group to begin building the hierarchy.",
        },
        emptyStateCampuses: {
            title: "No Campuses",
            description: "Add campuses to organise your reporting structure.",
        },
    },

    /* ── Analytics ────────────────────────────────────────────────────────── */
    analytics: {
        pageTitle: "Analytics",
        // Tabs
        tab: {
            overview: "Overview",
            metrics: "Metrics Analysis",
            trends: "Trends",
            compliance: "Compliance",
            quarterly: "Quarterly Summary",
        },
        // Section headings
        complianceTitle: "Report Compliance by Campus",
        trendsTitle: "Submission Trends",
        campusBreakdownTitle: "Campus Breakdown",
        statusBreakdownTitle: "Status Breakdown",
        metricTrendsTitle: "Key Metrics Over Time",
        goalVsAchievedTitle: "Goal vs. Achieved",
        yoyComparisonTitle: "Year-on-Year Comparison",
        campusMetricCompTitle: "Campus Metric Comparison",
        cumulativeTrendTitle: "Cumulative Trend",
        // Controls
        periodSelectorLabel: "Period",
        periodGranularityLabel: "Granularity",
        campusSelectorLabel: "Campus",
        groupSelectorLabel: "Group",
        metricSelectorLabel: "Metric",
        sectionSelectorLabel: "Section",
        exportButton: "Export",
        yearLabel: "Year",
        monthRangeLabel: "Month Range",
        // Granularity options
        granularity: {
            weekly: "Weekly",
            monthly: "Monthly",
            quarterly: "Quarterly",
            annual: "Annual",
        },
        // Chart labels
        chartLabels: {
            goal: "Goal",
            achieved: "Achieved",
            yoy: "Year on Year",
            submitted: "Submitted",
            approved: "Approved",
            count: "Count",
            value: "Value",
            percentage: "% Achieved",
        },
        // KPI labels
        kpi: {
            avgAchievementRate: "Avg. Achievement Rate",
            metricsTracked: "Metrics Tracked",
            campusesReporting: "Campuses Reporting",
            goalsSet: "Goals Set",
        },
        // State
        noData: "No data available for the selected period.",
        noMetricSelected: "Select a metric above to view the analysis.",
        loadingMetrics: "Loading metrics…",
        drafts: "Drafts",
        requiresEdits: "Requires Edits",
        quarterlyTitle: "Quarterly Summary",
        quarterlyComplianceLabel: "Q Compliance",
        quarterlySubmittedLabel: "Q Submitted",
        quarterlyApprovedLabel: "Q Approved",
        quarterlyQoqLabel: "vs. Previous Quarter",
        quarterlyNoData: "No data available for this quarter.",
        quarterlyTopCampuses: "Top Campuses This Quarter",
        quarterlySelector: "Quarter",
    },

    /* ── Notifications ─────────────────────────────────────────────────── */
    notifications: {
        pageTitle: "Inbox",
        markAllRead: "Mark all as read",
        emptyState: {
            title: "All Caught Up",
            description: "You have no new notifications.",
        },
        types: {
            REPORT_SUBMITTED: "Report Submitted",
            REPORT_EDIT_REQUESTED: "Edit Requested",
            REPORT_APPROVED: "Report Approved",
            REPORT_REVIEWED: "Report Reviewed",
            REPORT_LOCKED: "Report Locked",
            REPORT_UNLOCKED: "Report Unlocked",
            REPORT_EDIT_SUBMITTED: "Edit Submitted",
            REPORT_EDIT_APPROVED: "Edit Approved",
            REPORT_EDIT_REJECTED: "Edit Rejected",
            REPORT_UPDATE_REQUESTED: "Update Requested",
            REPORT_UPDATE_APPROVED: "Update Approved",
            REPORT_UPDATE_REJECTED: "Update Rejected",
            REPORT_DEADLINE_REMINDER: "Deadline Reminder",
            GOAL_UNLOCK_REQUESTED: "Goal Unlock Requested",
            GOAL_UNLOCK_APPROVED: "Goal Unlock Approved",
            GOAL_UNLOCK_REJECTED: "Goal Unlock Rejected",
            EMAIL_VERIFICATION_REQUIRED: "Email Verification",
            EMAIL_VERIFIED: "Email Verified",
            EMAIL_CHANGE_REQUESTED: "Email Change Requested",
            EMAIL_CHANGED: "Email Changed",
        },
        deadlineReminder: {
            fallbackRecipient: "there",
            fallbackReportTitle: "Report",
            title: "Deadline Reminder",
            messageTemplate: "Reminder: {reportTitle} is due on {deadline}.",
            actionLabel: "Submit Report",
        },
    },

    /* ── Common / Shared ────────────────────────────────────────────────── */
    common: {
        save: "Save",
        saving: "Saving…",
        cancel: "Cancel",
        confirm: "Confirm",
        delete: "Delete",
        edit: "Edit",
        view: "View",
        close: "Close",
        back: "Back",
        next: "Next",
        previous: "Previous",
        search: "Search",
        filter: "Filter",
        reset: "Reset",
        export: "Export",
        refresh: "Refresh",
        loading: "Loading…",
        submitting: "Submitting…",
        required: "Required",
        optional: "Optional",
        yes: "Yes",
        no: "No",
        all: "All",
        none: "None",
        unknown: "Unknown",
        activate: "Activate",
        deactivate: "Deactivate",
        noResultsTitle: "Nothing here yet",
        noResultsDescription: "Try adjusting your filters.",
        viewAll: "View all",
        successSave: "Saved successfully.",
        successDelete: "Deleted successfully.",
        errorDefault: "Something went wrong. Please try again.",
        errorNotFound: "The requested resource was not found.",
        errorUnauthorized: "You are not authorised to perform this action.",
        pagination: {
            showing: "Showing",
            to: "to",
            of: "of",
            results: "results",
        },
        darkMode: "dark mode",
        lightMode: "light mode",
        switchTo: "Switch to",
    },

    footer: {
        organization: "Harvesters International Christian Centre (HICC)",
        rights: "All rights reserved.",
        builtByLabel: "Built by",
        developerName: "S.D",
        developerUrl: "https://sotonye-dagogo.is-a.dev",
        links: [
            { label: "Home", href: "/" },
            { label: "How it works", href: "/how-it-works" },
            { label: "About", href: "/about" },
            { label: "Privacy", href: "/privacy" },
            { label: "Terms", href: "/terms" },
        ],
    },

    /* ── Profile ───────────────────────────────────────────────────────────── */
    profile: {
        pageTitle: "My Profile",
        editProfile: "Edit Profile",
        changePassword: "Change Password",
        accountInfoLabel: "Account Information",
        personalInfoLabel: "Personal Information",
        firstNameLabel: "First Name",
        lastNameLabel: "Last Name",
        emailLabel: "Email Address",
        phoneLabel: "Phone Number",
        roleLabel: "Role",
        campusLabel: "Campus",
        groupLabel: "Group",
        saveChanges: "Save Changes",
        saving: "Saving…",
        passwordSection: "Change Password",
        emailSecuritySection: "Email Verification & Change",
        emailVerificationLabel: "Email Verification",
        emailVerifiedBadge: "Verified",
        emailUnverifiedBadge: "Unverified",
        verificationStatusHint: "Verification protects your account and enables trusted email alerts.",
        verificationSentTo: "Verification email sent to",
        resendVerification: "Resend Verification Email",
        verificationEmailSent: "Verification email sent.",
        emailChangeLabel: "Change Email",
        newEmailLabel: "New Email Address",
        newEmailPlaceholder: "new-address@harvestersng.org",
        requestEmailChange: "Request Email Change",
        emailChangeRequested: "Email change confirmation sent.",
        pendingEmailLabel: "Pending Email",
        confirmViaEmailHint: "Confirm the link sent to your new email to complete this change.",
        currentPasswordLabel: "Current Password",
        newPasswordLabel: "New Password",
        confirmPasswordLabel: "Confirm New Password",
        updatePassword: "Update Password",
        passwordUpdated: "Password updated successfully.",
        profileUpdated: "Profile updated successfully.",
        memberSince: "Member Since",
        lastUpdated: "Last Updated",
        tabs: {
            profile: "Profile",
            security: "Security",
            appearance: "Appearance",
            notifications: "Notifications",
        },
    },

    /* ── Invite Links ─────────────────────────────────────────────────────── */
    invites: {
        pageTitle: "Invite Links",
        newInvite: "Generate Invite Link",
        copyLink: "Copy Link",
        copiedLink: "Copied!",
        revokeLink: "Revoke",
        targetRoleLabel: "Invite As",
        recipientEmailLabel: "Recipient Email",
        recipientEmailPlaceholder: "you@harvestersng.org",
        campusLabel: "Campus (optional)",
        groupLabel: "Group (optional)",
        expiresInLabel: "Expires In",
        noteLabel: "Internal Note",
        notePlaceholder: "e.g. For new Lagos campus admin",
        statusActive: "Active",
        statusUsed: "Used",
        statusExpired: "Expired",
        statusRevoked: "Revoked",
        expiresAtLabel: "Expires",
        usedAtLabel: "Used At",
        createdAtLabel: "Created",
        linkLabel: "Invite URL",
        generateButton: "Generate",
        emptyState: {
            title: "No Invite Links",
            description: "Generate a link to invite a new user to the system.",
        },
        expiryOptions: {
            "24": "24 hours",
            "48": "48 hours",
            "72": "72 hours (default)",
            "168": "7 days",
            "720": "30 days",
        },
        deleteConfirm: "Revoke this invite link? The URL will no longer work.",
    },
    /* ── Bug Reports ────────────────────────────────────────────────────── */
    bugReports: {
        pageTitle: "Report a Bug",
        managePageTitle: "Bug Reports",
        categoryLabel: "Issue Type",
        categoryPlaceholder: "Select an issue type",
        descriptionLabel: "Description",
        descriptionPlaceholder: "Describe the issue you encountered in detail...",
        screenshotLabel: "Screenshot (optional)",
        screenshotHint: "Upload a screenshot to help us understand the issue.",
        emailLabel: "Contact Email",
        emailPlaceholder: "you@harvestersng.org",
        submitButton: "Submit Bug Report",
        submitting: "Submitting...",
        submitSuccess: "Bug report submitted. Thank you!",
        statusLabel: "Status",
        adminNotesLabel: "Admin Notes",
        adminNotesPlaceholder: "Internal notes about this bug report...",
        categories: {
            UI_DISPLAY: "UI / Display Issue",
            NAVIGATION: "Navigation Problem",
            DATA_ISSUE: "Data Inaccuracy",
            PERFORMANCE: "Slow Performance",
            AUTHENTICATION: "Login / Authentication",
            REPORT_SUBMISSION: "Report Submission",
            NOTIFICATION: "Notification Issue",
            OTHER: "Other",
        },
        statuses: {
            OPEN: "Open",
            IN_PROGRESS: "In Progress",
            RESOLVED: "Resolved",
            CLOSED: "Closed",
        },
        emptyState: {
            title: "No Bug Reports",
            description: "No bug reports have been submitted yet.",
        },
        updateSuccess: "Bug report updated.",
    },
    /* ── Settings ───────────────────────────────────────────────────────── */
    settings: {
        pageTitle: "App Settings",
        appearanceSection: "Appearance",
        themeLabel: "Theme",
        themeDescription: "Choose how the app looks to you.",
        themeSystem: "System default",
        themeLight: "Light",
        themeDark: "Dark",
        notificationsSection: "Notification Preferences",
        emailNotificationsLabel: "Email Notifications",
        emailNotificationsDescription: "Receive report deadline and status updates via email.",
        inAppNotificationsLabel: "In-App Notifications",
        inAppNotificationsDescription: "Show notification badge and pop-ups in the app.",
        deadlineRemindersLabel: "Deadline Reminders",
        deadlineRemindersDescription: "Get reminders 24 h and 48 h before report deadlines.",
        pushNotificationsSection: "Push Notifications",
        pushNotificationsLabel: "Push Notifications",
        pushNotificationsDescription: "Receive real-time push notifications on this device.",
        pushEnabled: "Push notifications enabled.",
        pushDisabled: "Push notifications disabled.",
        pushNotSupported: "Push notifications are not supported in this browser.",
        pushPermissionDenied: "Permission denied. Enable notifications in your browser settings.",
        pushNotConfigured: "Push notifications are not configured for this environment.",
        enablePush: "Enable Push",
        disablePush: "Disable Push",
        saved: "Preferences saved.",
        savePreferences: "Save Preferences",
        unsavedChanges: "Unsaved changes",
    },
    /* ── Offline Page ────────────────────────────────────────────────────────── */
    offline: {
        title: "You're Offline",
        description: "It looks like you've lost your internet connection. Check your connection and try again.",
        retryButton: "Try Again",
        hint: "Previously viewed pages may still be accessible from cache.",
    },

    /* ── Error Pages ─────────────────────────────────────────────────────── */
    errors: {
        generic: "Something went wrong. Please try again.",
        notFoundTitle: "Page Not Found",
        notFoundDescription: "The page you are looking for does not exist.",
        notFoundCta: "Go to Dashboard",
        bugReportCta: "Report Bug",
        errorTitle: "Something Went Wrong",
        errorDescription: "An unexpected error occurred. Consider refreshing or filing a bug report.",
        errorCta: "Try Again",
        offlineTitle: "You're Offline",
        offlineDescription: "Check your internet connection and try again.",
        onlineTitle: "You're Back Online",
        onlineDescription: "Connection restored.",
        previewFailed: "Preview failed",
        generationFailed: "Generation failed",
    },

    /* ── Landing page (root /) ─────────────────────────────────────────────── */
    landing: {
        hero: {
            eyebrow: "Harvesters Reporting System",
            headline: "Every campus report, in one auditable, analytics-ready place.",
            subheadline:
                "Standardise weekly + monthly reporting across campuses and groups. Run review workflows, roll up to group / org level, and surface the insights leadership actually needs.",
            primaryCtaGuestLabel: "Sign in",
            primaryCtaGuestHref: "/login",
            primaryCtaAuthLabel: "Open my dashboard",
            secondaryCtaLabel: "How it works",
            secondaryCtaHref: "/how-it-works",
        },
        features: [
            {
                title: "Config-driven from end to end",
                body: "Roles, hierarchy levels, dashboards, email templates, cadence — all admin-editable through the substrate. No deploys for copy changes or workflow tweaks.",
            },
            {
                title: "Quick-form for ushers",
                body: "Service-day data entry that wires straight into the campus admin's report. Recurring assignment rules + auto-totals keep the numbers consistent.",
            },
            {
                title: "Aggregated rollups",
                body: "Monthly, quarterly, and yearly views computed live across any defined org level. One click into the aggregation engine from any report detail.",
            },
            {
                title: "Insights that matter",
                body: "Pearson correlations across template-defined metric groups, top-mover deltas, biggest-gap rankings — gated by a sample-size floor so the numbers stay honest.",
            },
            {
                title: "Safe by default",
                body: "Strict TypeScript, Zod-validated APIs, audit-tagged impersonation for safe role previews, additive-only DB migrations. Existing data is never at risk.",
            },
            {
                title: "Offline-tolerant",
                body: "Drafts auto-save locally and sync when you're back online. Push notifications + email are optional and gracefully degrade when the service isn't configured.",
            },
        ],
        quickLinksHeading: "Jump in",
        quickLinks: {
            authenticated: [
                { label: "Dashboard", href: "/dashboard" },
                { label: "Reports", href: "/reports" },
                { label: "Analytics", href: "/analytics" },
                { label: "How it works", href: "/how-it-works" },
            ],
            guest: [
                { label: "Sign in", href: "/login" },
                { label: "Have an invite?", href: "/join" },
                { label: "How it works", href: "/how-it-works" },
                { label: "About", href: "/about" },
            ],
        },
        welcomeBack: "Welcome back",
        signedOutBadge: "Not signed in",
        learnMore: "Learn more",
    },

    /* ── How It Works page ──────────────────────────────────────────────────── */
    howItWorks: {
        pageTitle: "How it works",
        pageSubtitle:
            "Concise walkthroughs by feature and role, with scenarios, FAQs, and in-page playgrounds.",
        intro:
            "Pick a tab below — each one walks through the typical flow, includes a short scenario, and ends with frequently-asked questions and a hands-on playground where applicable.",
        tabs: [
            {
                slug: "overview",
                title: "Overview",
                sections: [
                    {
                        heading: "What this platform is",
                        body:
                            "The Harvesters Reporting System replaces fragmented Excel + WhatsApp + Word workflows with a single auditable surface for campus reports, reviews, approvals, and analytics. Every value is traceable; every action is logged.",
                    },
                    {
                        heading: "How roles fit together",
                        body:
                            "Ushers enter raw service-day numbers via the quick form. Campus admins consolidate and submit the weekly / monthly report. Group admins and pastors review and roll up. CEO / Office of CEO / Church Ministry / SPO see scope-overview analytics first, with one-click access to aggregated reports.",
                    },
                    {
                        heading: "What's admin-editable",
                        body:
                            "Roles + capability bits, hierarchy levels, dashboard widget sets, email templates, role cadence (frequency + expected days + deadline), correlation defaults, PWA copy, invite defaults — all editable at runtime through Admin Config without a deploy.",
                    },
                ],
                faqs: [
                    {
                        q: "Do I need to be online to fill a report?",
                        a: "No. Drafts auto-save locally and sync when you're back online. The offline indicator in the corner shows the queue length.",
                    },
                    {
                        q: "What happens if I lose access mid-edit?",
                        a: "Your current draft survives. Sign back in and the form rehydrates with the values you'd entered.",
                    },
                ],
                playgroundIds: [],
            },
            {
                slug: "ushers",
                title: "For Ushers",
                sections: [
                    {
                        heading: "Quick-form basics",
                        body:
                            "When you sign in you land on the Quick Form page. Each card is one assignment — only the metrics your admin chose for you to fill, no goal context. Type in your numbers, the system auto-saves every 30 seconds, and tap Submit when you're done.",
                    },
                    {
                        heading: "Who decides which metrics you fill?",
                        body:
                            "A campus or group admin opens the template editor → Quick-form assignments tab and creates a rule for the USHER role. They pick which metrics, optionally restrict to specific campuses, and set a cadence (typically weekly Sunday + Wednesday).",
                    },
                    {
                        heading: "Where the values go",
                        body:
                            "Your submission flows directly into the campus admin's weekly / monthly report — no copy-paste. The campus admin sees a small 'auto-filled by usher' badge so they know which numbers came from you.",
                    },
                ],
                faqs: [
                    {
                        q: "What if I'm assigned to fill a metric I don't have data for?",
                        a: "Leave it blank. Save Draft. The campus admin can follow up directly or fill it themselves.",
                    },
                    {
                        q: "Can I edit a value after submitting?",
                        a: "Until the assignment is marked complete, yes. After completion, your campus admin handles edits.",
                    },
                ],
                playgroundIds: ["quick-form-demo"],
            },
            {
                slug: "campus-admin",
                title: "For Campus Admins",
                sections: [
                    {
                        heading: "Filling the campus report",
                        body:
                            "Open Reports → New report. The template auto-fills the title and period from its recurrence settings. Ushers' submissions are already in the corresponding cells. Add the rest, run a preview, and Submit when ready.",
                    },
                    {
                        heading: "Aggregated quick views",
                        body:
                            "On any report detail you'll see Monthly / Quarterly / Yearly chips — one click takes you to a server-aggregated rollup of all your campus's reports for that period. No extra setup.",
                    },
                    {
                        heading: "Auto-totals",
                        body:
                            "If your template has an auto-total metric (e.g. 'Total attendance' = Men + Women + Children), the cell is server-computed and read-only on the form, with a comment listing the source metrics.",
                    },
                ],
                faqs: [
                    {
                        q: "Can I unlock a metric an usher already filled?",
                        a: "Yes — the value is editable until the report is approved. After approval, request an unlock from your campus pastor.",
                    },
                ],
                playgroundIds: [],
            },
            {
                slug: "group-leadership",
                title: "For Group Admins / Pastors",
                sections: [
                    {
                        heading: "Scope overview at a glance",
                        body:
                            "Your dashboard lands on a scope-overview view: campus performance ranking, top-movers, compliance heatmap, period selector. From there, drill into any campus's reports without leaving the page.",
                    },
                    {
                        heading: "Approving + reviewing",
                        body:
                            "Submitted campus reports queue under 'Pending review'. Mark Reviewed once the data passes your check; if something's off, request edits with a reason — the campus admin gets notified inline + by email if the service is configured.",
                    },
                ],
                faqs: [
                    {
                        q: "How do I see a quarter or year roll-up?",
                        a: "From any campus report detail, click the Quarterly or Yearly chip. The aggregation engine computes it live across all source reports in the period.",
                    },
                ],
                playgroundIds: [],
            },
            {
                slug: "executive",
                title: "For CEO / SPO / Office of CEO / Church Ministry",
                sections: [
                    {
                        heading: "Org-wide scope overview",
                        body:
                            "Your dashboard shows group performance ranking, top campus, org compliance, recent submissions, pending review queue, and admin quick-links. The widget set is admin-editable from Admin Config → Dashboard layout.",
                    },
                    {
                        heading: "Insights",
                        body:
                            "InsightSummary card surfaces top-mover, biggest-gap, and compliance-delta sentences. CorrelationMatrix renders a Pearson heatmap when at least 5 paired samples exist (configurable).",
                    },
                ],
                faqs: [
                    {
                        q: "Can I preview the platform as another role?",
                        a: "Yes — superadmin can start a time-limited impersonation session. Read-only by default; switch to mutate mode if you need to take real actions. Every event is audit-logged.",
                    },
                ],
                playgroundIds: [],
            },
            {
                slug: "admin-config",
                title: "For Superadmin",
                sections: [
                    {
                        heading: "Admin Config substrate",
                        body:
                            "The Admin Config page is where every admin-editable bit lives: roles + capabilities, hierarchy levels, dashboard layout per role band, email templates, role cadence, correlation thresholds, PWA copy, invite defaults. Each namespace has a typed fallback in `config/*` — DB overrides take effect on next read with optimistic-lock conflict detection on save.",
                    },
                    {
                        heading: "Templates editor",
                        body:
                            "Templates → tabs: Sections & metrics for the data shape, Quick-form assignments for the recurring rule editor. Auto-sum panel sits at the section level — pick source metrics from the same section or, with a one-click opt-in, across the template.",
                    },
                    {
                        heading: "Impersonation",
                        body:
                            "Open the user menu → Preview as another role. Pick the role; for campus / group-scoped roles you must pick a target user so the preview inherits real campus + group context. Sessions auto-expire (default 30 min) and log every event.",
                    },
                ],
                faqs: [
                    {
                        q: "How do I roll back a bad config change?",
                        a: "Each namespace tab has a Reset to defaults button — that writes a tombstone row marking the namespace as fallback, restoring the typed defaults from `config/*`.",
                    },
                    {
                        q: "Can I add new roles at runtime?",
                        a: "Labels and capabilities for existing roles are admin-editable. Adding a brand-new role enum requires a deploy because user.role is a Postgres enum — but you can re-purpose any non-SUPERADMIN role with a fresh label + capability set.",
                    },
                ],
                playgroundIds: ["correlation-demo"],
            },
        ],
        playgroundComingSoon: "Hands-on playground — coming soon for this section.",
        relatedHelpHeading: "Related help",
    },

    /* ── Need Help? anchor + page → tab map ────────────────────────────────── */
    helpAnchors: {
        "/dashboard": "overview",
        "/reports": "campus-admin",
        "/reports/new": "campus-admin",
        "/reports/aggregate": "group-leadership",
        "/quick-form": "ushers",
        "/templates": "admin-config",
        "/admin-config": "admin-config",
        "/analytics": "executive",
        "/users": "admin-config",
        "/invites": "admin-config",
        "/imports": "admin-config",
    },
    helpLinkLabel: "Need help?",
    helpLinkAria: "Open help for this page",

    /* ── Impersonation (superadmin role preview) ──────────────────────────── */
    impersonation: {
        bannerReadOnlyTitle: "Previewing as",
        bannerReadOnlyHint: "Read-only — actions will not apply.",
        bannerMutateTitle: "Previewing & MUTATING as",
        bannerMutateHint: "Mutate mode — changes take real effect.",
        bannerExpiresIn: "Expires in",
        bannerForUser: "for",
        modeReadOnlyLabel: "Read only",
        modeMutateLabel: "Mutate",
        switchToMutate: "Switch to mutate",
        switchToReadOnly: "Switch to read-only",
        exit: "Exit preview",
        exiting: "Exiting…",
        startTitle: "Preview the app as another role",
        startSubtitle:
            "Time-limited preview. Your SUPERADMIN identity stays the actor of record; every action is audit-tagged.",
        startSubmit: "Start preview",
        startCancel: "Cancel",
        roleLabel: "Role",
        userLabel: "Specific user (optional)",
        userLabelRequired: "Specific user (required for campus/group-scoped roles)",
        targetRequired:
            "This role is scoped to a campus or group — pick a real user so the preview inherits their scope. Without a target the preview can't materialise their assignments.",
        previewNoCampusBanner:
            "You're previewing this scoped role without a target user, so there's no campus context to materialise assignments against. Exit and start over with a target user picked.",
        modeLabel: "Mode",
        readOnlyDescription:
            "Walk flows safely. Mutating endpoints will return 403 and be logged as blocked.",
        mutateDescription:
            "Actions take real effect on production data. Audit rows are tagged with your impersonation context.",
        toasts: {
            started: "Preview started.",
            stopped: "Preview ended.",
            modeSwitched: "Mode switched.",
            mutationBlocked:
                "Read-only preview — switch to mutate mode to apply changes, or exit preview.",
            startFailed: "Could not start preview.",
        },
        rowActionLabel: "Preview as this user",
        managePageTitle: "Impersonation log",
        managePageSubtitle: "Past sessions and per-event timeline.",
        eventTypeLabels: {
            STARTED: "Started",
            STOPPED: "Stopped",
            MODE_CHANGED: "Mode changed",
            MUTATION_BLOCKED: "Mutation blocked",
            MUTATION_APPLIED: "Mutation applied",
            PAGE_VISITED: "Page visited",
            AUTH_REJECTED: "Auth rejected",
            EVENT_LIMIT_REACHED: "Event limit reached",
        },
    },

    /* ── Report quick views (aggregated rollup CTAs) ──────────────────────── */
    reportsQuickViews: {
        heading: "Aggregated views",
        regionLabel: "Aggregated report quick views",
        noDataTooltip: "No source data yet for this rollup",
    },

    /* ── Users list ──────────────────────────────────────────────────────────── */
    usersList: {
        statusLabels: {
            ACTIVE: "Active",
            INACTIVE: "Inactive",
            ACTIVATION_PENDING: "Awaiting activation",
            PENDING_INVITE: "Invited",
        },
        statusColors: {
            ACTIVE: "green",
            INACTIVE: "default",
            ACTIVATION_PENDING: "blue",
            PENDING_INVITE: "orange",
        },
        filterAll: "All",
        showInvited: "Show invited & pre-registered",
        directoryHint: "Includes invited and pre-registered users alongside active accounts.",
    },

    /* ── Admin Config ────────────────────────────────────────────────────────── */
    adminConfig: {
        pageTitle: "Admin Config",
        subtitle: "Tune the substrate that powers roles, dashboards, imports, and onboarding.",
        namespaceLabels: {
            roles: "Roles & Capabilities",
            hierarchy: "Hierarchy Levels",
            dashboardLayout: "Dashboard Layout",
            templatesMapping: "Template & Metric Mappings",
            imports: "Import Defaults",
            pwaInstall: "PWA Install Copy",
            bulkInvites: "Invite Defaults",
            analytics: "Analytics Defaults",
            emailTemplates: "Email Templates",
            roleCadence: "Role Cadence",
            correlation: "Insights & Correlation",
            impersonationLog: "Impersonation log",
        },
        actions: {
            save: "Save namespace",
            reset: "Reset to defaults",
            diff: "Show diff vs fallback",
        },
        toasts: {
            saved: "Configuration saved.",
            reset: "Reverted to defaults.",
            conflict: "Someone else updated this namespace. Reload and re-apply.",
            saveFailed: "Could not save configuration. Try again.",
        },
        labels: {
            currentVersion: "Current version",
            usingFallback: "Using built-in defaults",
            usingDbOverride: "Using database override",
            updatedBy: "Updated by",
            namespace: "Namespace",
        },
        emptyState: {
            title: "No overrides yet",
            description: "This namespace is currently served from the built-in defaults. Save changes here to take over.",
        },
    },

    /* ── Imports ─────────────────────────────────────────────────────────────── */
    imports: {
        pageTitle: "Spreadsheet Imports",
        subtitle: "Bring CSV/XLSX data into reports with mapped columns and a safe preview.",
        steps: {
            upload: "Upload",
            map: "Map columns",
            preview: "Preview",
            commit: "Commit",
        },
        actions: {
            uploadFile: "Choose file",
            saveMapping: "Save mapping profile",
            useSavedMapping: "Use saved mapping",
            validate: "Validate",
            commit: "Commit import",
            cancel: "Cancel job",
        },
        toasts: {
            jobCreated: "Import job created.",
            mappingSaved: "Mapping saved.",
            validated: "Validation complete.",
            committed: "Import committed.",
            failed: "Import failed.",
            cancelled: "Import cancelled.",
        },
        emptyState: {
            title: "No active imports",
            description: "Upload a spreadsheet to start a new import job.",
        },
        outcomeLabels: {
            OK: "Ready",
            WARNING: "Warning",
            ERROR: "Error",
            COMMITTED: "Committed",
        },
    },

    /* ── Quick Form (Usher / Data Entry) ───────────────────────────────────── */
    quickForm: {
        pageTitle: "My Assignments",
        subtitle: "Fill in the metric values you have been assigned.",
        fillTitle: "Quick Fill",
        fillSubtitle: "Enter values for assigned metrics only.",
        emptyState: {
            title: "No active assignments",
            description: "When someone assigns you a form, it will appear here.",
        },
        statusLabels: {
            active: "Active",
            completed: "Completed",
            cancelled: "Cancelled",
            overdue: "Overdue",
        },
        actions: {
            startFill: "Start filling",
            saveDraft: "Save draft",
            submit: "Submit values",
        },
        autosave: {
            saving: "Saving…",
            saved: "Draft saved",
            failed: "Could not save draft",
        },
    },

    /* ── PWA Install Banner ─────────────────────────────────────────────────── */
    pwaInstall: {
        bannerTitle: "Install the Harvesters Reporting app",
        bannerSubtitle: "Get one-tap access, faster load, and offline drafts. Install in under a minute.",
        installCta: "Install",
        snoozeCta: "Maybe later",
        neverCta: "Don't show again",
        platformInstructions: {
            IOS: "Tap the Share icon in Safari, then choose “Add to Home Screen”.",
            ANDROID: "Tap the menu (⋮) in Chrome, then choose “Install app”.",
            DESKTOP: "Use the install icon in your address bar (Chrome, Edge) or the browser menu.",
        },
        push: {
            title: "Enable notifications",
            subtitle: "Get instant pings for approvals, deadlines, and assignments.",
            enableCta: "Enable",
            laterCta: "Maybe later",
            blockedHelp: "Notifications are blocked in your browser settings. Allow them and try again.",
        },
    },

    /* ── Bulk Invites + Pre-register + Activation ──────────────────────────── */
    bulkInvites: {
        pageTitle: "Bulk Invites",
        subtitle: "Create many invite links in one go.",
        modes: {
            link: "Generate invite links",
            preregister: "Pre-register users",
        },
        actions: {
            addRow: "Add another",
            paste: "Paste from clipboard",
            send: "Send invites",
            preregister: "Create activation links",
            downloadCsv: "Download outcomes (CSV)",
        },
        outcomeLabels: {
            created: "Invite created",
            already_invited: "Already invited",
            already_registered: "Already registered",
            failed: "Failed",
            preregistered: "Activation sent",
            activation_skipped: "User already active",
        },
        emptyState: {
            title: "No bulk batches yet",
            description: "Add rows above to create your first bulk invite or pre-register batch.",
        },
        helpers: {
            sharedDefaults: "Shared defaults are used unless a row overrides them.",
            csvHint: "Paste rows as: email, role, campus|group (one per line).",
        },
    },

    preregister: {
        emailSubject: "Activate your Harvesters Reporting account",
        emailIntro: "Your account has been pre-created. Click below to set your password and sign in.",
        actionLabel: "Activate account",
        expiryNote: "This link will expire in",
    },

    activation: {
        pageTitle: "Activate your account",
        subtitle: "Set a new password to finish activating.",
        invalidTitle: "Activation link invalid or expired",
        invalidDescription: "Ask your admin to send a new activation link.",
        successTitle: "Account activated",
        successDescription: "You can now sign in with your new password.",
        actionSubmit: "Activate and sign in",
    },

    /* ── SEO / Meta ──────────────────────────────────────────────────────────── */
    seo: {
        appDescription: "The central report management platform for Harvesters International Christian Centre — campus report submission, review, and analytics.",
        // Auth pages
        loginDescription: "Sign in to the Harvesters Reporting System to access your campus reports and analytics.",
        registerDescription: "Create your Harvesters Reporting System account to start managing campus reports.",
        forgotPasswordDescription: "Reset your Harvesters Reporting System password.",
        resetPasswordDescription: "Set a new password for your Harvesters Reporting System account.",
        joinTitle: "You're Invited",
        joinDescription: "You have been invited to join the Harvesters Reporting System — the central platform for campus report submission and analytics at Harvesters International Christian Centre.",
        // Dashboard pages
        dashboardDescription: "View your reporting dashboard — KPIs, recent activity, and upcoming deadlines.",
        reportsDescription: "Manage, submit, and review campus reports across Harvesters campuses.",
        newReportDescription: "Create and submit a new campus report.",
        reportDetailDescription: "View the full details and history of this campus report.",
        reportEditDescription: "Edit and update this campus report.",
        templatesDescription: "Manage report templates used across campuses for standardised data collection.",
        newTemplateDescription: "Create a new report template to standardise campus reporting.",
        templateDetailDescription: "View and manage this report template.",
        usersDescription: "Manage system users — roles, campus assignments, and access levels.",
        userDetailDescription: "View and manage this user's profile and role assignment.",
        orgDescription: "Manage the organisation hierarchy — groups, campuses, and zones.",
        analyticsDescription: "Analyse report data, trends, and compliance metrics across all campuses.",
        inboxDescription: "Stay up to date with report approvals, edit requests, and system notifications.",
        goalsDescription: "Set and track performance goals to measure campus progress against targets.",
        invitesDescription: "Generate and manage invite links to onboard new users to the system.",
        bugReportsDescription: "Report a bug or issue you encountered in the Harvesters Reporting System.",
        bugReportsManageDescription: "Review and manage all bug reports submitted by system users.",
        profileDescription: "Manage your profile, security settings, and notification preferences.",
    },
} satisfies AppContent;

export type ContentKey = typeof CONTENT;
