/**
 * config/content.ts
 * Every user-visible string lives here.
 * Components import CONTENT and reference by key — zero string literals in JSX.
 */

// AppContent is declared in types/global.d.ts inside `declare global` — no import needed.

export const CONTENT = {
    /* ── Navigation ──────────────────────────────────────────────────────── */
    nav: {
        dashboard: "Dashboard",
        reports: "Reports",
        templates: "Templates",
        analytics: "Analytics",
        users: "Users",
        org: "Organisation",
        inbox: "Inbox",
        invites: "Invite Links",
        settings: "Settings",
        goals: "Goals",
        bugReports: "Report a Bug",
        bugReportsManage: "Bug Reports",
        profile: "Profile",
        logout: "Logout",
        backToDashboard: "Back to Dashboard",
    },

    /* ── Auth ─────────────────────────────────────────────────────────────── */
    auth: {
        loginTitle: "Sign In",
        loginSubtitle: "Welcome back to the Harvesters Reporting System",
        emailLabel: "Email Address",
        emailPlaceholder: "you@harvesters.org",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter your password",
        loginButton: "Sign In",
        loggingIn: "Signing in…",
        forgotPassword: "Forgot password?",
        noAccount: "Don't have an account?",
        registerLink: "Create an account",
        registerTitle: "Create Account",
        registerSubtitle: "Set up your Harvesters Reporting System account",
        firstNameLabel: "First Name",
        lastNameLabel: "Last Name",
        firstNamePlaceholder: "Your first name",
        lastNamePlaceholder: "Your last name",
        phoneLabel: "Phone Number",
        phonePlaceholder: "+234 800 000 0000",
        registerButton: "Create Account",
        alreadyHaveAccount: "Already have an account?",
        loginLink: "Sign in",
        forgotTitle: "Reset Password",
        forgotSubtitle: "Enter your email and we'll send reset instructions",
        sendResetLink: "Send Reset Link",
        resetTitle: "Set New Password",
        resetSubtitle: "Choose a strong new password",
        newPasswordLabel: "New Password",
        confirmPasswordLabel: "Confirm Password",
        resetButton: "Reset Password",
        joinTitle: "Join via Invite",
        joinSubtitle: "Complete your registration using an invite link",
        errors: {
            invalidCredentials: "Invalid email or password.",
            serverError: "Something went wrong. Please try again.",
            emailRequired: "Email is required.",
            emailInvalid: "Please enter a valid email address.",
            passwordRequired: "Password is required.",
            passwordsDoNotMatch: "Passwords do not match.",
            passwordTooShort: "Password must be at least 8 characters.",
            invalidToken: "This invite link is invalid or has expired.",
        },
        accountInfoLabel: "Account Information",
        passwordChangedSuccess: "Password changed successfully.",
        currentPasswordLabel: "Current Password",
        changePasswordAction: "Change Password",
        profileTabLabel: "Profile",
        passwordTabLabel: "Password",
        inviteInvalidTitle: "Invalid Invite Link",
        inviteExpiredTitle: "Invite Link Expired",
        inviteUsedTitle: "Invite Already Used",
        goToLogin: "Go to Login",
        registrationSuccessTitle: "Registration Successful",
        registrationSuccessMessage: "Your account has been created. You can now sign in.",
        redirectingIn: "Redirecting to login in",
        inviteRoleLabel: "You have been invited as",
        rememberMe: "Remember me",
        haveInvite: "Have an invite link?",
        joinWithInvite: "Join with invite",
        noInvite: "No invite link?",
        registerWithoutInvite: "Create a free account",
    },

    /* ── Reports ────────────────────────────────────────────────────────── */
    reports: {
        pageTitle: "Reports",
        newReport: "New Report",
        submitReport: "Submit Report",
        saveDraft: "Save Draft",
        requestEdit: "Request Edit",
        approveReport: "Approve",
        markReviewed: "Mark Reviewed",
        lockReport: "Lock Report",
        viewReport: "View Report",
        editReport: "Edit Report",
        viewHistory: "View History",
        requestUpdate: "Request Update",
        filterByStatus: "Filter by status",
        filterByCampus: "Filter by campus",
        filterByPeriod: "Filter by period",
        filterByTemplate: "Filter by template",
        searchPlaceholder: "Search reports…",
        periodLabel: "Period",
        statusLabel: "Status",
        campusLabel: "Campus",
        groupLabel: "Group",
        deadlineLabel: "Deadline",
        submittedByLabel: "Submitted By",
        submittedAtLabel: "Submitted At",
        reviewedByLabel: "Reviewed By",
        approvedByLabel: "Approved By",
        lockedAtLabel: "Locked At",
        notesLabel: "Notes",
        notesPlaceholder: "Add any notes or context…",
        dataEntryBadge: "Data Entry",
        fieldGoal: "Goal",
        fieldAchieved: "Achieved",
        fieldYoY: "YoY Goal",
        fieldGoalComment: "Add goal comment",
        fieldAchievedComment: "Add context",
        fieldYoYComment: "Add YoY comment",
        metricComment: "Add comment",
        commentPlaceholder: "Optional context or note…",
        goalPrefilledTooltip: "Pre-filled from set goals — not editable while filling a report",
        goalFromSource: "Goal source",
        goalNotSet: "No goal set",
        goalLocked: "Goal locked",
        goalsLoading: "Loading goals…",
        goalsPrefilledBadge: "goals pre-filled",
        noGoalsSet: "No goals set for this period — enter values manually",
        statVsGoal: "vs Goal",
        statVsYoY: "vs Last Year",
        requiredFilled: "required filled",
        liveStats: "Live Statistics",
        statOverallGoal: "Overall Goal Progress",
        statYoYGrowth: "Year-on-Year Growth",
        statMetricsWithGoal: "Metrics with Goals",
        metricsFormTitle: "Report Data",
        sectionRequired: "Required",
        sectionOptional: "Optional",
        emptyState: {
            title: "No Reports Found",
            description: "No reports match your current filters.",
            newReportCta: "Submit your first report",
        },
        deleteConfirm: "Are you sure you want to delete this report?",
        submitConfirm: "Submit this report for review?",
        approveConfirm: "Approve this report?",
        lockConfirm: "Lock this report? This cannot be undone.",
        editRequestTitle: "Request Edit",
        editRequestReasonLabel: "Reason for Edit",
        editRequestReasonPlaceholder: "Describe what needs to be corrected…",
        editRequestSubmit: "Submit Edit Request",
        updateRequestTitle: "Request Update",
        updateReasonLabel: "Reason for Update",
        updateReasonPlaceholder: "Explain why this update is needed…",
        updateRequestSubmit: "Submit Update Request",
        editRequestDraftTitle: "Draft Edit",
        editRequestApprove: "Approve Edit",
        editRequestReject: "Reject Edit",
        historyTitle: "Report History",
        auditTrailTitle: "Audit Trail",
        eventLabels: {
            CREATED: "Report Created",
            SUBMITTED: "Report Submitted",
            EDIT_REQUESTED: "Edits Requested",
            EDIT_SUBMITTED: "Edit Submitted",
            EDIT_APPROVED: "Edit Approved",
            EDIT_REJECTED: "Edit Rejected",
            EDIT_APPLIED: "Edit Applied",
            TRANSLATED: "Translated",
            APPROVED: "Report Approved",
            REVIEWED: "Report Reviewed",
            LOCKED: "Report Locked",
            UNLOCKED: "Report Unlocked",
            DEADLINE_PASSED: "Deadline Passed",
            UPDATE_REQUESTED: "Update Requested",
            UPDATE_APPROVED: "Update Approved",
            UPDATE_REJECTED: "Update Rejected",
            DATA_ENTRY_CREATED: "Data Entry Submitted",
            TEMPLATE_VERSION_NOTE: "Template Version Updated",
            AUTO_APPROVED: "Auto-Approved",
        },
        sections: {
            attendanceTitle: "Weekly Attendance",
            salvationsTitle: "Salvations & First Timers",
            discipleshipTitle: "Discipleship",
            tithesTitle: "Tithes & Offerings",
            workersTitle: "Workers",
            outreachTitle: "Outreach",
            youthTitle: "Youth",
            childrenTitle: "Children",
            mediaTitle: "Media & Digital",
            prayerTitle: "Prayer",
            infrastructureTitle: "Infrastructure & Facilities",
        },
        status: {
            DRAFT: "Draft",
            SUBMITTED: "Submitted",
            REQUIRES_EDITS: "Requires Edits",
            APPROVED: "Approved",
            REVIEWED: "Reviewed",
            LOCKED: "Locked",
        },
        actions: {
            submit: "Submit",
            approve: "Approve",
            review: "Mark Reviewed",
            lock: "Lock",
            unlock: "Unlock",
            requestEdit: "Request Edit",
        },
        columnLabels: {
            report: "Report",
            title: "Title",
            campus: "Campus",
            period: "Period",
            status: "Status",
            submittedBy: "Submitted By",
            submittedAt: "Submitted At",
            deadline: "Deadline",
            createdAt: "Created",
            lockedAt: "Locked At",
            actions: "",
        },
        filterLabels: {
            status: "Status",
            campus: "Campus",
            period: "Period",
            template: "Template",
            all: "All",
        },
        metadata: {
            title: "Details",
            templateLabel: "Template",
            periodTypeLabel: "Period Type",
            yearLabel: "Year",
            weekLabel: "Week",
            monthLabel: "Month",
            createdByLabel: "Created By",
            deadlineLabel: "Deadline",
            lockedAtLabel: "Locked At",
        },
        export: {
            button: "Export (.xlsx)",
            dialogTitle: "Export Reports",
            scopeLabel: "Export Scope",
            scopeAll: "All filtered reports",
            scopeSelected: "Selected reports only",
            groupingLabel: "Group by",
            groupingNone: "None",
            groupingCampus: "Campus",
            groupingMonth: "Month",
            groupingQuarter: "Quarter",
            contentLabel: "Include",
            contentMetrics: "Metric values",
            contentGoals: "Goal values",
            contentComments: "Comments",
            contentStatus: "Status history",
            formatLabel: "Format",
            formatSingleSheet: "Single sheet",
            formatMultiSheet: "One sheet per campus",
            exportButtonLabel: "Export",
            cancelButtonLabel: "Cancel",
            listFilename: "harvesters-reports",
            sheetList: "Reports",
            sheetMeta: "Overview",
            sheetMetrics: "Metrics",
            colTitle: "Title",
            colCampus: "Campus",
            colPeriod: "Period",
            colStatus: "Status",
            colTemplate: "Template",
            colDeadline: "Deadline",
            colCreatedAt: "Created",
            colSubmittedBy: "Submitted By",
            colNotes: "Notes",
            colSection: "Section",
            colMetric: "Metric",
            colAchieved: "Achieved",
            colGoal: "Goal",
            colPercentage: "% of Goal",
            colComment: "Comment",
        },
    },

    /* ── Templates ────────────────────────────────────────────────────────── */
    templates: {
        pageTitle: "Report Templates",
        newTemplate: "New Template",
        editTemplate: "Edit Template",
        previewTemplate: "Preview",
        publishTemplate: "Publish",
        archiveTemplate: "Archive",
        setDefault: "Set as Default",
        versionsLabel: "Version History",
        goalPromptTitle: "Set Goals for This Template?",
        goalPromptDescription: "This template captures goals for some metrics. Setting goals now lets fillers see progress against targets in the report form.",
        goalPromptConfirm: "Set Goals Now",
        goalPromptSkip: "Set Goals Later",
        templateSaved: "Template saved.",
        templateCreated: "Template created.",
        nameLabel: "Template Name",
        namePlaceholder: "e.g. Standard Campus Weekly Report",
        descriptionLabel: "Description",
        descriptionPlaceholder: "Brief description of this template's purpose",
        addSection: "Add Section",
        addMetric: "Add Metric",
        removeSection: "Remove Section",
        sectionLabel: "Section",
        sectionsLabel: "Sections",
        sectionNameLabel: "Section Name",
        metricNameLabel: "Metric Name",
        fieldTypeLabel: "Field Type",
        calculationTypeLabel: "Calculation Method",
        isRequiredLabel: "Required",
        capturesGoalLabel: "Captures Goal",
        capturesAchievedLabel: "Captures Achieved",
        capturesYoYLabel: "Captures YoY Goal",
        defaultBadge: "Default",
        createTemplate: "Create Template",
        emptySections: "No sections yet. Click Add Section to start building this template.",
        emptyMetrics: "No metrics yet. Add a metric below.",
        emptyState: {
            title: "No Templates",
            description: "Create a report template to start collecting data.",
        },
    },

    /* ── Goals ─────────────────────────────────────────────────────────────── */
    goals: {
        pageTitle: "Goals",
        setGoal: "Set Goal",
        editGoal: "Edit Goal",
        requestUnlock: "Request Edit",
        approveUnlock: "Approve",
        rejectUnlock: "Reject",
        targetValueLabel: "Target Value",
        yearLabel: "Year",
        monthLabel: "Month",
        modeLabel: "Goal Mode",
        lockedBadge: "Locked",
        pendingUnlockBadge: "Unlock Pending",
        unlockReasonLabel: "Reason for Unlock",
        unlockReasonPlaceholder: "Explain why this goal needs to be changed\u2026",
        cancelEdit: "Cancel",
        modeAnnual: "Annual \u2014 same target each month",
        modeMonthly: "Monthly \u2014 set per month individually",
        campusLabel: "Campus",
        allCampuses: "All Campuses",
        annualTargetLabel: "Annual Target (applies to all 12 months)",
        saveGoals: "Save Goals",
        savedGoals: "Goals saved successfully.",
        templateLabel: "Template",
        months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        lockedNote: "Locked \u2014 submit an unlock request to change this goal",
        noTemplate: "No active template found. Create a template first.",
        saveAll: "Save All Goals",
        metricColumn: "Metric",
        annualTargetShort: "Target",
        bulkNote: "Set annual targets for all campuses in a single view.",
        noGoalSet: "—",
        emptyState: {
            title: "No Goals Set",
            description: "Goals help track expected performance against actuals.",
        },
    },

    /* ── Dashboard ────────────────────────────────────────────────────────── */
    dashboard: {
        pageTitle: "Dashboard",
        kpi: {
            totalReports: "Total Reports",
            pendingReview: "Pending Review",
            approvedReports: "Approved",
            complianceRate: "Compliance Rate",
            submittedOnTime: "On-Time Submissions",
            overdueReports: "Overdue",
            activeTemplates: "Active Templates",
            totalCampuses: "Total Campuses",
            totalUsers: "Total Users",
            drafts: "Drafts",
            requiresEdits: "Requires Edits",
            quarterlyCompliance: "Quarter Compliance",
        },
        welcomeBack: "Welcome back",
        recentActivity: "Recent Activity",
        noActivity: "No recent activity.",
        upcomingDeadlines: "Upcoming Deadlines",
        noDeadlines: "No upcoming deadlines.",
        cta: {
            pendingApproval: (n: number) => `${n} report${n === 1 ? "" : "s"} pending your approval`,
            pendingReview: (n: number) => `${n} approved report${n === 1 ? "" : "s"} awaiting your review sign-off`,
            draftReports: (n: number) => `You have ${n} draft report${n === 1 ? "" : "s"} in progress`,
            requiresEdits: (n: number) => `${n} of your report${n === 1 ? "" : "s"} require${n === 1 ? "s" : ""} edits`,
            weeklyReportDue: (period: string) => `You have a weekly report due for ${period}`,
            viewReports: "View Reports",
        },
        memberLobby: {
            title: "Welcome to Harvesters Reporting",
            subtitle: "Your account has been created successfully. An administrator will assign you a role to get started.",
            waitingLabel: "Awaiting role assignment",
            currentRole: "Current role",
            contactAdmin: "If you believe this is an error, please contact your campus administrator.",
        },
    },

    /* ── Users ───────────────────────────────────────────────────────────── */
    users: {
        pageTitle: "Users",
        inviteUser: "Invite User",
        editUser: "Edit User",
        deactivateUser: "Deactivate",
        activateUser: "Activate",
        resetPassword: "Reset Password",
        nameLabel: "Name",
        emailLabel: "Email",
        roleLabel: "Role",
        campusLabel: "Campus",
        groupLabel: "Group",
        statusLabel: "Status",
        activeStatus: "Active",
        inactiveStatus: "Inactive",
        searchPlaceholder: "Search users…",
        emptyState: {
            title: "No Users Found",
            description: "No users match your current filters.",
        },
        confirmDeactivate: "Deactivate this user? They will no longer be able to log in.",
        confirmActivate: "Reactivate this user?",
        roles: {
            SUPERADMIN: "Superadmin",
            SPO: "SPO",
            CEO: "CEO",
            OFFICE_OF_CEO: "Office of CEO",
            CHURCH_MINISTRY: "Church Ministry",
            GROUP_PASTOR: "Group Pastor",
            GROUP_ADMIN: "Group Admin",
            CAMPUS_PASTOR: "Campus Pastor",
            CAMPUS_ADMIN: "Campus Admin",
            DATA_ENTRY: "Data Entry",
            MEMBER: "Member",
        },
        recentReports: "Recent Reports",
        noReports: "No reports submitted yet.",
    },

    /* ── Organisation ────────────────────────────────────────────────────── */
    org: {
        pageTitle: "Organisation",
        newGroup: "New Group",
        newCampus: "New Campus",
        editGroup: "Edit Group",
        editCampus: "Edit Campus",
        groupNameLabel: "Group Name",
        campusNameLabel: "Campus Name",
        countryLabel: "Country",
        locationLabel: "Location",
        leaderLabel: "Group Leader",
        adminLabel: "Campus Admin",
        campusesLabel: "Campuses",
        membersLabel: "Members",
        emptyStateGroups: {
            title: "No Groups",
            description: "Add an org group to begin building the hierarchy.",
        },
        emptyStateCampuses: {
            title: "No Campuses",
            description: "Add campuses to organise your reporting structure.",
        },
    },

    /* ── Analytics ────────────────────────────────────────────────────────── */
    analytics: {
        pageTitle: "Analytics",
        // Tabs
        tab: {
            overview: "Overview",
            metrics: "Metrics Analysis",
            trends: "Trends",
            compliance: "Compliance",
            quarterly: "Quarterly Summary",
        },
        // Section headings
        complianceTitle: "Report Compliance by Campus",
        trendsTitle: "Submission Trends",
        campusBreakdownTitle: "Campus Breakdown",
        statusBreakdownTitle: "Status Breakdown",
        metricTrendsTitle: "Key Metrics Over Time",
        goalVsAchievedTitle: "Goal vs. Achieved",
        yoyComparisonTitle: "Year-on-Year Comparison",
        campusMetricCompTitle: "Campus Metric Comparison",
        cumulativeTrendTitle: "Cumulative Trend",
        // Controls
        periodSelectorLabel: "Period",
        periodGranularityLabel: "Granularity",
        campusSelectorLabel: "Campus",
        groupSelectorLabel: "Group",
        metricSelectorLabel: "Metric",
        sectionSelectorLabel: "Section",
        exportButton: "Export",
        yearLabel: "Year",
        monthRangeLabel: "Month Range",
        // Granularity options
        granularity: {
            weekly: "Weekly",
            monthly: "Monthly",
            quarterly: "Quarterly",
            annual: "Annual",
        },
        // Chart labels
        chartLabels: {
            goal: "Goal",
            achieved: "Achieved",
            yoy: "Year on Year",
            submitted: "Submitted",
            approved: "Approved",
            count: "Count",
            value: "Value",
            percentage: "% Achieved",
        },
        // KPI labels
        kpi: {
            avgAchievementRate: "Avg. Achievement Rate",
            metricsTracked: "Metrics Tracked",
            campusesReporting: "Campuses Reporting",
            goalsSet: "Goals Set",
        },
        // State
        noData: "No data available for the selected period.",
        noMetricSelected: "Select a metric above to view the analysis.",
        loadingMetrics: "Loading metrics…",
        drafts: "Drafts",
        requiresEdits: "Requires Edits",
        quarterlyTitle: "Quarterly Summary",
        quarterlyComplianceLabel: "Q Compliance",
        quarterlySubmittedLabel: "Q Submitted",
        quarterlyApprovedLabel: "Q Approved",
        quarterlyQoqLabel: "vs. Previous Quarter",
        quarterlyNoData: "No data available for this quarter.",
        quarterlyTopCampuses: "Top Campuses This Quarter",
        quarterlySelector: "Quarter",
    },

    /* ── Notifications ─────────────────────────────────────────────────── */
    notifications: {
        pageTitle: "Inbox",
        markAllRead: "Mark all as read",
        emptyState: {
            title: "All Caught Up",
            description: "You have no new notifications.",
        },
        types: {
            REPORT_SUBMITTED: "Report Submitted",
            REPORT_EDIT_REQUESTED: "Edit Requested",
            REPORT_APPROVED: "Report Approved",
            REPORT_REVIEWED: "Report Reviewed",
            REPORT_LOCKED: "Report Locked",
            REPORT_UNLOCKED: "Report Unlocked",
            REPORT_EDIT_SUBMITTED: "Edit Submitted",
            REPORT_EDIT_APPROVED: "Edit Approved",
            REPORT_EDIT_REJECTED: "Edit Rejected",
            REPORT_UPDATE_REQUESTED: "Update Requested",
            REPORT_UPDATE_APPROVED: "Update Approved",
            REPORT_UPDATE_REJECTED: "Update Rejected",
            REPORT_DEADLINE_REMINDER: "Deadline Reminder",
            GOAL_UNLOCK_REQUESTED: "Goal Unlock Requested",
            GOAL_UNLOCK_APPROVED: "Goal Unlock Approved",
            GOAL_UNLOCK_REJECTED: "Goal Unlock Rejected",
        },
    },

    /* ── Common / Shared ────────────────────────────────────────────────── */
    common: {
        save: "Save",
        saving: "Saving…",
        cancel: "Cancel",
        confirm: "Confirm",
        delete: "Delete",
        edit: "Edit",
        view: "View",
        close: "Close",
        back: "Back",
        next: "Next",
        previous: "Previous",
        search: "Search",
        filter: "Filter",
        reset: "Reset",
        export: "Export",
        loading: "Loading…",
        submitting: "Submitting…",
        required: "Required",
        optional: "Optional",
        yes: "Yes",
        no: "No",
        all: "All",
        none: "None",
        unknown: "Unknown",
        activate: "Activate",
        deactivate: "Deactivate",
        noResultsTitle: "Nothing here yet",
        noResultsDescription: "Try adjusting your filters.",
        viewAll: "View all",
        successSave: "Saved successfully.",
        successDelete: "Deleted successfully.",
        errorDefault: "Something went wrong. Please try again.",
        errorNotFound: "The requested resource was not found.",
        errorUnauthorized: "You are not authorised to perform this action.",
        pagination: {
            showing: "Showing",
            to: "to",
            of: "of",
            results: "results",
        },
        darkMode: "dark mode",
        lightMode: "light mode",
        switchTo: "Switch to",
    },

    /* ── Profile ───────────────────────────────────────────────────────────── */
    profile: {
        pageTitle: "My Profile",
        editProfile: "Edit Profile",
        changePassword: "Change Password",
        accountInfoLabel: "Account Information",
        personalInfoLabel: "Personal Information",
        firstNameLabel: "First Name",
        lastNameLabel: "Last Name",
        emailLabel: "Email Address",
        phoneLabel: "Phone Number",
        roleLabel: "Role",
        campusLabel: "Campus",
        groupLabel: "Group",
        saveChanges: "Save Changes",
        saving: "Saving…",
        passwordSection: "Change Password",
        currentPasswordLabel: "Current Password",
        newPasswordLabel: "New Password",
        confirmPasswordLabel: "Confirm New Password",
        updatePassword: "Update Password",
        passwordUpdated: "Password updated successfully.",
        profileUpdated: "Profile updated successfully.",
        memberSince: "Member Since",
        lastUpdated: "Last Updated",
        tabs: {
            profile: "Profile",
            security: "Security",
            appearance: "Appearance",
            notifications: "Notifications",
        },
    },

    /* ── Invite Links ─────────────────────────────────────────────────────── */
    invites: {
        pageTitle: "Invite Links",
        newInvite: "Generate Invite Link",
        copyLink: "Copy Link",
        copiedLink: "Copied!",
        revokeLink: "Revoke",
        targetRoleLabel: "Invite As",
        campusLabel: "Campus (optional)",
        groupLabel: "Group (optional)",
        expiresInLabel: "Expires In",
        noteLabel: "Internal Note",
        notePlaceholder: "e.g. For new Lagos campus admin",
        statusActive: "Active",
        statusUsed: "Used",
        statusExpired: "Expired",
        statusRevoked: "Revoked",
        expiresAtLabel: "Expires",
        usedAtLabel: "Used At",
        createdAtLabel: "Created",
        linkLabel: "Invite URL",
        generateButton: "Generate",
        emptyState: {
            title: "No Invite Links",
            description: "Generate a link to invite a new user to the system.",
        },
        expiryOptions: {
            "24": "24 hours",
            "48": "48 hours",
            "72": "72 hours (default)",
            "168": "7 days",
            "720": "30 days",
        },
        deleteConfirm: "Revoke this invite link? The URL will no longer work.",
    },
    /* ── Bug Reports ────────────────────────────────────────────────────── */
    bugReports: {
        pageTitle: "Report a Bug",
        managePageTitle: "Bug Reports",
        categoryLabel: "Issue Type",
        categoryPlaceholder: "Select an issue type",
        descriptionLabel: "Description",
        descriptionPlaceholder: "Describe the issue you encountered in detail...",
        screenshotLabel: "Screenshot (optional)",
        screenshotHint: "Upload a screenshot to help us understand the issue.",
        emailLabel: "Contact Email",
        emailPlaceholder: "your.email@example.com",
        submitButton: "Submit Bug Report",
        submitting: "Submitting...",
        submitSuccess: "Bug report submitted. Thank you!",
        statusLabel: "Status",
        adminNotesLabel: "Admin Notes",
        adminNotesPlaceholder: "Internal notes about this bug report...",
        categories: {
            UI_DISPLAY: "UI / Display Issue",
            NAVIGATION: "Navigation Problem",
            DATA_ISSUE: "Data Inaccuracy",
            PERFORMANCE: "Slow Performance",
            AUTHENTICATION: "Login / Authentication",
            REPORT_SUBMISSION: "Report Submission",
            NOTIFICATION: "Notification Issue",
            OTHER: "Other",
        },
        statuses: {
            OPEN: "Open",
            IN_PROGRESS: "In Progress",
            RESOLVED: "Resolved",
            CLOSED: "Closed",
        },
        emptyState: {
            title: "No Bug Reports",
            description: "No bug reports have been submitted yet.",
        },
        updateSuccess: "Bug report updated.",
    },
    /* ── Settings ───────────────────────────────────────────────────────── */
    settings: {
        pageTitle: "App Settings",
        appearanceSection: "Appearance",
        themeLabel: "Theme",
        themeDescription: "Choose how the app looks to you.",
        themeSystem: "System default",
        themeLight: "Light",
        themeDark: "Dark",
        notificationsSection: "Notification Preferences",
        emailNotificationsLabel: "Email Notifications",
        emailNotificationsDescription: "Receive report deadline and status updates via email.",
        inAppNotificationsLabel: "In-App Notifications",
        inAppNotificationsDescription: "Show notification badge and pop-ups in the app.",
        deadlineRemindersLabel: "Deadline Reminders",
        deadlineRemindersDescription: "Get reminders 24 h and 48 h before report deadlines.",
        pushNotificationsSection: "Push Notifications",
        pushNotificationsLabel: "Push Notifications",
        pushNotificationsDescription: "Receive real-time push notifications on this device.",
        pushEnabled: "Push notifications enabled.",
        pushDisabled: "Push notifications disabled.",
        pushNotSupported: "Push notifications are not supported in this browser.",
        pushPermissionDenied: "Permission denied. Enable notifications in your browser settings.",
        enablePush: "Enable Push",
        disablePush: "Disable Push",
        saved: "Preferences saved.",
        savePreferences: "Save Preferences",
    },
    /* ── Offline Page ────────────────────────────────────────────────────────── */
    offline: {
        title: "You're Offline",
        description: "It looks like you've lost your internet connection. Check your connection and try again.",
        retryButton: "Try Again",
        hint: "Previously viewed pages may still be accessible from cache.",
    },

    /* ── Error Pages ─────────────────────────────────────────────────────── */
    errors: {
        generic: "Something went wrong. Please try again.",
        notFoundTitle: "Page Not Found",
        notFoundDescription: "The page you are looking for does not exist.",
        notFoundCta: "Go to Dashboard",
        bugReportCta: "Report Bug",
        errorTitle: "Something Went Wrong",
        errorDescription: "An unexpected error occurred. Consider refreshing or filing a bug report.",
        errorCta: "Try Again",
        offlineTitle: "You're Offline",
        offlineDescription: "Check your internet connection and try again.",
        onlineTitle: "You're Back Online",
        onlineDescription: "Connection restored.",
    },

    /* ── SEO / Meta ──────────────────────────────────────────────────────────── */
    seo: {
        appDescription: "The central report management platform for Harvesters International Christian Centre — campus report submission, review, and analytics.",
        // Auth pages
        loginDescription: "Sign in to the Harvesters Reporting System to access your campus reports and analytics.",
        registerDescription: "Create your Harvesters Reporting System account to start managing campus reports.",
        forgotPasswordDescription: "Reset your Harvesters Reporting System password.",
        resetPasswordDescription: "Set a new password for your Harvesters Reporting System account.",
        joinTitle: "You're Invited",
        joinDescription: "You have been invited to join the Harvesters Reporting System — the central platform for campus report submission and analytics at Harvesters International Christian Centre.",
        // Dashboard pages
        dashboardDescription: "View your reporting dashboard — KPIs, recent activity, and upcoming deadlines.",
        reportsDescription: "Manage, submit, and review campus reports across Harvesters campuses.",
        newReportDescription: "Create and submit a new campus report.",
        reportDetailDescription: "View the full details and history of this campus report.",
        reportEditDescription: "Edit and update this campus report.",
        templatesDescription: "Manage report templates used across campuses for standardised data collection.",
        newTemplateDescription: "Create a new report template to standardise campus reporting.",
        templateDetailDescription: "View and manage this report template.",
        usersDescription: "Manage system users — roles, campus assignments, and access levels.",
        userDetailDescription: "View and manage this user's profile and role assignment.",
        orgDescription: "Manage the organisation hierarchy — groups, campuses, and zones.",
        analyticsDescription: "Analyse report data, trends, and compliance metrics across all campuses.",
        inboxDescription: "Stay up to date with report approvals, edit requests, and system notifications.",
        goalsDescription: "Set and track performance goals to measure campus progress against targets.",
        invitesDescription: "Generate and manage invite links to onboard new users to the system.",
        bugReportsDescription: "Report a bug or issue you encountered in the Harvesters Reporting System.",
        bugReportsManageDescription: "Review and manage all bug reports submitted by system users.",
        profileDescription: "Manage your profile, security settings, and notification preferences.",
    },
} satisfies AppContent;

export type ContentKey = typeof CONTENT;
