/**
 * config/roles.ts
 * ROLE_CONFIG: authoritative capability map for every role.
 * Used to drive nav filtering, permission checks, and dashboard routing.
 */

import { UserRole } from "@/types/global";
import { APP_ROUTES } from "./routes";
import { CONTENT } from "./content";

export const ROLE_CONFIG: Record<UserRole, RoleConfig> = {
    [UserRole.SUPERADMIN]: {
        role: UserRole.SUPERADMIN,
        label: CONTENT.users.roles.SUPERADMIN,
        hierarchyOrder: 0,
        dashboardRoute: APP_ROUTES.dashboard,
        dashboardMode: "system",
        canCreateReports: true,
        canFillReports: false,
        canSubmitReports: false,
        canRequestEdits: false,
        canApproveReports: false,
        canMarkReviewed: false,
        canLockReports: true,
        canManageTemplates: true,
        canDataEntry: false,
        canManageUsers: true,
        canManageOrg: true,
        canSetGoals: true,
        canApproveGoalUnlock: true,
        reportVisibilityScope: "all",
    },
    [UserRole.SPO]: {
        role: UserRole.SPO,
        label: CONTENT.users.roles.SPO,
        hierarchyOrder: 1,
        dashboardRoute: APP_ROUTES.dashboard,
        dashboardMode: "analytics",
        canCreateReports: false,
        canFillReports: false,
        canSubmitReports: false,
        canRequestEdits: true,
        canApproveReports: false,
        canMarkReviewed: true,
        canLockReports: false,
        canManageTemplates: false,
        canDataEntry: false,
        canManageUsers: false,
        canManageOrg: false,
        canSetGoals: true,
        canApproveGoalUnlock: true,
        reportVisibilityScope: "all",
    },
    [UserRole.CEO]: {
        role: UserRole.CEO,
        label: CONTENT.users.roles.CEO,
        hierarchyOrder: 2,
        dashboardRoute: APP_ROUTES.dashboard,
        dashboardMode: "analytics",
        canCreateReports: false,
        canFillReports: false,
        canSubmitReports: false,
        canRequestEdits: true,
        canApproveReports: false,
        canMarkReviewed: true,
        canLockReports: false,
        canManageTemplates: false,
        canDataEntry: false,
        canManageUsers: false,
        canManageOrg: false,
        canSetGoals: true,
        canApproveGoalUnlock: true,
        reportVisibilityScope: "all",
    },
    [UserRole.CHURCH_MINISTRY]: {
        role: UserRole.CHURCH_MINISTRY,
        label: CONTENT.users.roles.CHURCH_MINISTRY,
        hierarchyOrder: 3,
        dashboardRoute: APP_ROUTES.dashboard,
        dashboardMode: "analytics",
        canCreateReports: false,
        canFillReports: false,
        canSubmitReports: false,
        canRequestEdits: true,
        canApproveReports: true,
        canMarkReviewed: false,
        canLockReports: false,
        canManageTemplates: false,
        canDataEntry: false,
        canManageUsers: false,
        canManageOrg: false,
        canSetGoals: false,
        canApproveGoalUnlock: false,
        reportVisibilityScope: "all",
    },
    [UserRole.GROUP_PASTOR]: {
        role: UserRole.GROUP_PASTOR,
        label: CONTENT.users.roles.GROUP_PASTOR,
        hierarchyOrder: 4,
        dashboardRoute: APP_ROUTES.dashboard,
        dashboardMode: "report-reviewed",
        canCreateReports: false,
        canFillReports: false,
        canSubmitReports: false,
        canRequestEdits: true,
        canApproveReports: false,
        canMarkReviewed: true,
        canLockReports: false,
        canManageTemplates: false,
        canDataEntry: false,
        canManageUsers: false,
        canManageOrg: false,
        canSetGoals: true,
        canApproveGoalUnlock: true,
        reportVisibilityScope: "all",
    },
    [UserRole.GROUP_ADMIN]: {
        role: UserRole.GROUP_ADMIN,
        label: CONTENT.users.roles.GROUP_ADMIN,
        hierarchyOrder: 5,
        dashboardRoute: APP_ROUTES.dashboard,
        dashboardMode: "report-review",
        canCreateReports: false,
        canFillReports: false,
        canSubmitReports: false,
        canRequestEdits: true,
        canApproveReports: true,
        canMarkReviewed: false,
        canLockReports: false,
        canManageTemplates: false,
        canDataEntry: true,
        canManageUsers: false,
        canManageOrg: false,
        canSetGoals: true,
        canApproveGoalUnlock: false,
        reportVisibilityScope: "all",
    },
    [UserRole.CAMPUS_PASTOR]: {
        role: UserRole.CAMPUS_PASTOR,
        label: CONTENT.users.roles.CAMPUS_PASTOR,
        hierarchyOrder: 6,
        dashboardRoute: APP_ROUTES.dashboard,
        dashboardMode: "report-review",
        canCreateReports: true,
        canFillReports: true,
        canSubmitReports: true,
        canRequestEdits: false,
        canApproveReports: false,
        canMarkReviewed: false,
        canLockReports: false,
        canManageTemplates: false,
        canDataEntry: false,
        canManageUsers: false,
        canManageOrg: false,
        canSetGoals: false,
        canApproveGoalUnlock: false,
        reportVisibilityScope: "campus",
    },
    [UserRole.CAMPUS_ADMIN]: {
        role: UserRole.CAMPUS_ADMIN,
        label: CONTENT.users.roles.CAMPUS_ADMIN,
        hierarchyOrder: 7,
        dashboardRoute: APP_ROUTES.dashboard,
        dashboardMode: "report-fill",
        canCreateReports: true,
        canFillReports: true,
        canSubmitReports: true,
        canRequestEdits: false,
        canApproveReports: false,
        canMarkReviewed: false,
        canLockReports: false,
        canManageTemplates: false,
        canDataEntry: false,
        canManageUsers: false,
        canManageOrg: false,
        canSetGoals: false,
        canApproveGoalUnlock: false,
        reportVisibilityScope: "campus",
    },
    [UserRole.DATA_ENTRY]: {
        role: UserRole.DATA_ENTRY,
        label: CONTENT.users.roles.DATA_ENTRY,
        hierarchyOrder: 8,
        dashboardRoute: APP_ROUTES.reports,
        dashboardMode: "report-fill",
        canCreateReports: true,
        canFillReports: true,
        canSubmitReports: true,
        canRequestEdits: false,
        canApproveReports: false,
        canMarkReviewed: false,
        canLockReports: false,
        canManageTemplates: false,
        canDataEntry: true,
        canManageUsers: false,
        canManageOrg: false,
        canSetGoals: false,
        canApproveGoalUnlock: false,
        reportVisibilityScope: "campus",
    },
    [UserRole.MEMBER]: {
        role: UserRole.MEMBER,
        label: CONTENT.users.roles.MEMBER,
        hierarchyOrder: 9,
        dashboardRoute: APP_ROUTES.member.dashboard,
        dashboardMode: "report-fill",
        canCreateReports: false,
        canFillReports: false,
        canSubmitReports: false,
        canRequestEdits: false,
        canApproveReports: false,
        canMarkReviewed: false,
        canLockReports: false,
        canManageTemplates: false,
        canDataEntry: false,
        canManageUsers: false,
        canManageOrg: false,
        canSetGoals: false,
        canApproveGoalUnlock: false,
        reportVisibilityScope: "own",
    },
};

/* ── Helper utilities ─────────────────────────────────────────────────────── */

/** Roles allowed to submit reports on behalf of campuses */
export const REPORT_SUBMITTER_ROLES: UserRole[] = [
    UserRole.CAMPUS_PASTOR,
    UserRole.CAMPUS_ADMIN,
    UserRole.DATA_ENTRY,
    UserRole.GROUP_ADMIN,
];

/** Roles that approve / review reports (above campus level) */
export const REPORT_REVIEWER_ROLES: UserRole[] = [
    UserRole.GROUP_ADMIN,
    UserRole.GROUP_PASTOR,
    UserRole.CHURCH_MINISTRY,
    UserRole.CEO,
    UserRole.SPO,
    UserRole.SUPERADMIN,
];

/** All roles that have access to /leader/* routes */
export const LEADER_ROLES: UserRole[] = [
    UserRole.CAMPUS_ADMIN,
    UserRole.CAMPUS_PASTOR,
    UserRole.DATA_ENTRY,
    UserRole.GROUP_ADMIN,
    UserRole.GROUP_PASTOR,
    UserRole.CHURCH_MINISTRY,
    UserRole.CEO,
    UserRole.SPO,
];

/** Check if a role can perform an action on a report at a given status */
export function canTransitionReport(
    role: UserRole,
    currentStatus: string,
    action: keyof RoleConfig,
): boolean {
    const config = ROLE_CONFIG[role];
    return !!config[action];
}

/** Get the display label for any role */
export function getRoleLabel(role: UserRole): string {
    return ROLE_CONFIG[role]?.label ?? role;
}

/** Get dashboard route for a role */
export function getDashboardRoute(role: UserRole): string {
    return ROLE_CONFIG[role]?.dashboardRoute ?? APP_ROUTES.dashboard;
}
